#### Prepare files

In [16]:
import json
import pandas as pd

records = []
pred_dir = "/home/csgrad/mbhosale/phd/MrFair/LLaVA-Rad/results/llavarad_fair_mi" 
with open(pred_dir+"/merged_pred.jsonl", "r") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        rec = json.loads(line)      # urlsafe json parser, keeps strings intact
        records.append(rec)

# Build a DataFrame out of it
df = pd.DataFrame.from_records(records)
# "id" (this id is patient ID and Study ID) We need patient ID only for fairness analysis
df['subject_id'] = df['id'].apply(lambda x: int(x.split("_")[0]))

In [17]:
df

,id,query,reference,prediction,subject_id
0,10046166_57379357,<image>\nProvide a description of the findings...,Frontal and lateral views of the chest were ob...,The patient is status post median sternotomy a...,10046166
1,10046166_57977208,<image>\nProvide a description of the findings...,"In comparison with the study of ___, there is ...","In comparison with the study of ___, there is ...",10046166
2,10268877_50042142,<image>\nProvide a description of the findings...,The ET tube is 3.5 cm above the carina. The N...,Single portable view of the chest. Endotrache...,10268877
3,10268877_50239281,<image>\nProvide a description of the findings...,Left PICC tip is seen terminating in the regio...,"In comparison with the study of ___, there is ...",10268877
4,10268877_51513702,<image>\nProvide a description of the findings...,Single AP portable view of the chest. No prio...,Single portable view of the chest. The lungs ...,10268877
...,...,...,...,...,...
2456,15131736_52449022,<image>\nProvide a description of the findings...,"Lung volumes are low, similar when compared to...",The heart is severely enlarged. There is pulm...,15131736
2457,19075045_58071016,<image>\nProvide a description of the findings...,Sternotomy with valve prosthesis. Endotrachea...,The endotracheal tube is in appropriate positi...,19075045
2458,19991135_51777681,<image>\nProvide a description of the findings...,PA and lateral radiographs of the chest were a...,Frontal and lateral views of the chest were ob...,19991135
2459,12185775_57910301,<image>\nProvide a description of the findings...,The ET and NG tubes have been removed. A right...,Compared to the prior study there is no signif...,12185775
2460,16508811_50818829,<image>\nProvide a description of the findings...,A left-sided internal jugular catheter is stab...,Compared to the prior study there is no signif...,16508811

In [18]:
# Lets load the demographic data
patients_data = pd.read_csv("/a2il/data/mbhosale/MrFair/physionet.org/mimc-cxr-jpeg/patients.csv")

In [19]:
patients_data

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod
0,10000032,F,52,2180,2014 - 2016,2180-09-09
1,10000048,F,23,2126,2008 - 2010,NaN
2,10000058,F,33,2168,2020 - 2022,NaN
3,10000068,F,19,2160,2008 - 2010,NaN
4,10000084,M,72,2160,2017 - 2019,2161-02-13
...,...,...,...,...,...,...
364622,19999828,F,46,2147,2017 - 2019,NaN
364623,19999829,F,28,2186,2008 - 2010,NaN
364624,19999840,M,58,2164,2008 - 2010,2164-09-17
364625,19999914,F,49,2158,2017 - 2019,NaN
364626,19999987,F,57,2145,2011 - 2013,NaN

In [20]:
merged_df = df.merge(patients_data, on='subject_id', how='left', validate='m:1')

In [21]:
merged_df[merged_df['dod'].isna()]

,id,query,reference,prediction,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod
30,10449297_52837403,<image>\nProvide a description of the findings...,AP upright and lateral views of the chest were...,The heart size is mildly enlarged. The aorta ...,10449297,NaN,NaN,NaN,NaN,NaN
31,10449297_54773340,<image>\nProvide a description of the findings...,Comparison is made to ___. In\n comparison to...,Frontal and lateral views of the chest were ob...,10449297,NaN,NaN,NaN,NaN,NaN
32,10523725_56078456,<image>\nProvide a description of the findings...,Frontal and lateral views of the chest. The l...,The patient is status post median sternotomy a...,10523725,M,76.0,2138.0,2011 - 2013,NaN
33,10715477_50563564,<image>\nProvide a description of the findings...,"In comparison with the study of ___, there is ...","In comparison with the study of ___, the monit...",10715477,NaN,NaN,NaN,NaN,NaN
34,10715477_51185902,<image>\nProvide a description of the findings...,Right internal jugular sheath ends at upper SV...,"In comparison with the study of ___, there is ...",10715477,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2447,15114531_54616688,<image>\nProvide a description of the findings...,There is a left PICC which terminates within t...,The lungs are clear. The cardiomediastinal si...,15114531,F,60.0,2154.0,2008 - 2010,NaN
2448,17270742_50989704,<image>\nProvide a description of the findings...,Dominant central cavitary lesions are similar ...,The lungs are hyperinflated with bilateral dif...,17270742,NaN,NaN,NaN,NaN,NaN
2450,12699874_57974904,<image>\nProvide a description of the findings...,Again seen is a large right hydropneumothorax ...,PA and lateral views of the chest were obtaine...,12699874,M,85.0,2129.0,2011 - 2013,NaN
2451,15881535_58897728,<image>\nProvide a description of the findings...,"The cardiomediastinal silhouette, pulmonary va...",The lungs are clear without focal consolidatio...,15881535,M,66.0,2184.0,2008 - 2010,NaN
2455,19720782_51067581,<image>\nProvide a description of the findings...,Since the prior study the pseudotumor (fluid i...,The right major fissure is thickened and there...,19720782,NaN,NaN,NaN,NaN,NaN

In [22]:
merged_df['gender'].isna().value_counts()

gender
False    2332
True      129
Name: count, dtype: int64

In [23]:
merged_df['anchor_age'].isna().value_counts()

anchor_age
False    2332
True      129
Name: count, dtype: int64

In [24]:
merged_df['dod'].isna().value_counts()

dod
False    1506
True      955
Name: count, dtype: int64

In [25]:
# We do need age and gender for fairness analysis, so we will just drop the rows missing
merged_df = merged_df.dropna(subset=['anchor_age', 'gender'])

In [26]:
merged_df['gender'].value_counts()

gender
M    1301
F    1031
Name: count, dtype: int64

In [27]:
import numpy as np
bins   = [0, 44, 65, np.inf]
labels = ['0–44', '44–65', '65+']
merged_df = merged_df.copy()

merged_df.loc[:, 'age_group'] = pd.cut(
    merged_df['anchor_age'],
    bins=bins,
    labels=labels,
    right=True,
    include_lowest=True
)

In [28]:
merged_df['age_group'].value_counts()

age_group
65+      1151
44–65    1080
0–44      101
Name: count, dtype: int64

In [29]:
# Lets separate out the results according to demographic groups
merged_df[merged_df['gender'] == 'M'][['id','query','reference','prediction']] \
    .to_json(pred_dir+'/gender_m.jsonl', orient='records', lines=True)

merged_df[merged_df['gender'] == 'F'][['id','query','reference','prediction']] \
    .to_json(pred_dir+'/gender_f.jsonl', orient='records', lines=True)

merged_df[merged_df['age_group'] == '0–44'][['id','query','reference','prediction']] \
    .to_json(pred_dir+'/age_0_44.jsonl', orient='records', lines=True)

merged_df[merged_df['age_group'] == '44–65'][['id','query','reference','prediction']] \
    .to_json(pred_dir+'/age_44_65.jsonl', orient='records', lines=True)

merged_df[merged_df['age_group'] == '65+'][['id','query','reference','prediction']] \
    .to_json(pred_dir+'/age_65_inf.jsonl', orient='records', lines=True)

In [30]:
admissions = pd.read_csv("/a2il/data/mbhosale/MrFair/physionet.org/mimc-cxr-jpeg/admissions.csv")

In [31]:
admissions['insurance'].value_counts()

insurance
Medicare     244576
Private      173399
Medicaid     104229
Other         14006
No charge       463
Name: count, dtype: int64

In [32]:
admissions['race'].value_counts()

race
WHITE                                        336538
BLACK/AFRICAN AMERICAN                        75482
OTHER                                         19788
WHITE - OTHER EUROPEAN                        13972
UNKNOWN                                       13870
HISPANIC/LATINO - PUERTO RICAN                10903
HISPANIC OR LATINO                             8287
ASIAN                                          7809
ASIAN - CHINESE                                7644
WHITE - RUSSIAN                                6597
BLACK/CAPE VERDEAN                             6205
HISPANIC/LATINO - DOMINICAN                    6070
BLACK/CARIBBEAN ISLAND                         3875
BLACK/AFRICAN                                  3495
UNABLE TO OBTAIN                               3478
PATIENT DECLINED TO ANSWER                     2162
PORTUGUESE                                     2082
ASIAN - SOUTH EAST ASIAN                       1973
WHITE - EASTERN EUROPEAN                       1886
HISPANIC/LATINO - GUATEMALAN                   1858
ASIAN - ASIAN INDIAN                           1661
WHITE - BRAZILIAN                              1526
HISPANIC/LATINO - SALVADORAN                   1320
AMERICAN INDIAN/ALASKA NATIVE                  1247
HISPANIC/LATINO - COLUMBIAN                     920
HISPANIC/LATINO - MEXICAN                       883
SOUTH AMERICAN                                  774
HISPANIC/LATINO - HONDURAN                      725
ASIAN - KOREAN                                  664
HISPANIC/LATINO - CUBAN                         641
HISPANIC/LATINO - CENTRAL AMERICAN              603
MULTIPLE RACE/ETHNICITY                         596
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER       494
Name: count, dtype: int64

In [33]:
# We need to p
import numpy as np
race = admissions['race']

# define boolean masks
conds = [
    race.str.contains(r'^WHITE', case=False, na=False),
    race.str.contains(r'^BLACK', case=False, na=False),
    race.str.contains(r'^ASIAN', case=False, na=False),
    race.str.contains(r'HISPANIC', case=False, na=False),
    race.str.contains(r'AMERICAN INDIAN', case=False, na=False),
    race.str.contains(r'HAWAIIAN|PACIFIC ISLANDER', case=False, na=False),
    race.str.contains(r'^OTHER$', case=False, na=False),
    race.str.contains(r'DECLINED|UNABLE TO OBTAIN', case=False, na=False),
    race.str.contains(r'^UNKNOWN$', case=False, na=False),
]

# corresponding labels
labels = [
    'White',
    'Black or African American',
    'Asian',
    'Hispanic or Latino',
    'American Indian or Alaska Native',
    'Native Hawaiian or Pacific Islander',
    'Other',
    'Declined / Unable to obtain',
    'Unknown',
]
admissions['race_major'] = np.select(conds, labels, default='Other')
admissions['race_major'].value_counts()

race_major
White                                  360519
Black or African American               89057
Hispanic or Latino                      32210
Other                                   23240
Asian                                   19751
Unknown                                 13870
Declined / Unable to obtain              5640
American Indian or Alaska Native         1247
Native Hawaiian or Pacific Islander       494
Name: count, dtype: int64

In [34]:
admissions['marital_status'].value_counts()

marital_status
MARRIED     229134
SINGLE      206232
WIDOWED      56687
DIVORCED     40356
Name: count, dtype: int64

In [35]:
admissions = (admissions.drop_duplicates(subset=['subject_id'], keep='first')[['subject_id','insurance','race_major','marital_status']])

In [36]:
admissions['insurance'].value_counts()

insurance
Private      86139
Medicare     85524
Medicaid     38022
Other         6952
No charge      187
Name: count, dtype: int64

In [37]:
admissions['race_major'].value_counts()

race_major
White                                  147528
Black or African American               28659
Hispanic or Latino                      11981
Other                                   10766
Unknown                                 10352
Asian                                    9660
Declined / Unable to obtain              3771
American Indian or Alaska Native          481
Native Hawaiian or Pacific Islander       254
Name: count, dtype: int64

In [38]:
admissions['marital_status'].value_counts()

marital_status
MARRIED     95614
SINGLE      82797
WIDOWED     20226
DIVORCED    14119
Name: count, dtype: int64

In [39]:
merged_df = merged_df.merge(admissions, on='subject_id', how='left', validate='m:1')

In [40]:
merged_df['insurance'].value_counts()

insurance
Medicare     1552
Private       479
Medicaid      276
Other          21
No charge       4
Name: count, dtype: int64

In [41]:
merged_df['race_major'].value_counts()

race_major
White                               1621
Black or African American            489
Asian                                 85
Hispanic or Latino                    67
Other                                 37
Unknown                               22
Declined / Unable to obtain            7
American Indian or Alaska Native       4
Name: count, dtype: int64

In [42]:
merged_df['marital_status'].value_counts()

marital_status
MARRIED     1046
SINGLE       703
WIDOWED      344
DIVORCED     239
Name: count, dtype: int64

In [43]:
merged_df[merged_df['race_major'] == 'White'][['id','query','reference','prediction']].to_json(pred_dir+'/race_white.jsonl', orient='records', lines=True)
merged_df[merged_df['race_major'] == 'Black or African American'][['id','query','reference','prediction']].to_json(pred_dir+'/race_black.jsonl', orient='records', lines=True)
merged_df[merged_df['race_major'] == 'Asian'][['id','query','reference','prediction']].to_json(pred_dir+'/race_asian.jsonl', orient='records', lines=True)
merged_df[merged_df['race_major'] == 'Other'][['id','query','reference','prediction']].to_json(pred_dir+'/race_other.jsonl', orient='records', lines=True)
merged_df[merged_df['race_major'] == 'Hispanic or Latino'][['id','query','reference','prediction']].to_json(pred_dir+'/race_hispanic.jsonl', orient='records', lines=True)

In [44]:
merged_df.to_json('../results/llavarad/merged_demographics.jsonl', orient='records', lines=True)

### Fairness Analysis

#### 1. Gender

In [83]:
!python ../llava/eval/rrg_eval/run.py ../results/llavarad/gender_m.jsonl --run_name gender_m

[2025-07-03 20:59:47,344] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CheXbert:   0%|                                           | 0/5 [00:00<?, ?it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

bootstrap micro f1 95% CI:   0%|                        | 0/500 [00:00<?, ?it/s]
bootstrap micro f1 95% CI:   2%|▎             | 11/500 [00:00<00:04, 102.92it/s]
bootstrap micro f1 95% CI:   5%|▋             | 23/500 [00:00<00:04, 110.16it/s]
bootstrap micro f1 95% CI:   7%|▉             | 35/500 [00:00<00:04, 112.62it/s]
bootstrap micro f1 95% CI:   9%|█▎            | 47/500 [00:00<00:03, 113.78it/s]
bootstrap micro f1 95% CI:  12%|█▋            | 59/500 [00:00<00:03, 114.43it/s]
bootstrap micro f1 95% CI:  14%|█▉            | 71/500 [00:00<00:03, 114.10it/s]
bootstrap micro f1 95% CI:  17%|██▎           | 83/500 [00:00<00:03, 113.93it/s]
bootstrap micro f1 95% CI:  19%|██▋           | 95/500 [00:00<00:03, 114.38it/s]
bootstrap micro f1 95% CI:  21%|██▊          | 107/500 [00:00<00:03, 114.99it/s]
bootstrap micro f1 95% CI:  24%|███          | 119/500 [00:01<00:03, 114.94it/s]
bootstrap micro f1 95% CI:  26%|███▍         | 131/500 [00:01<00:03, 115.50it/s]
bootstrap micro f1 95% CI:  29%|███▋         | 143/500 [00:01<00:03, 115.52it/s]
bootstrap micro f1 95% CI:  31%|████         | 155/500 [00:01<00:02, 115.61it/s]
bootstrap micro f1 95% CI:  33%|████▎        | 167/500 [00:01<00:02, 116.00it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 179/500 [00:01<00:02, 115.80it/s]
bootstrap micro f1 95% CI:  38%|████▉        | 191/500 [00:01<00:02, 115.73it/s]
bootstrap micro f1 95% CI:  41%|█████▎       | 203/500 [00:01<00:02, 115.53it/s]
bootstrap micro f1 95% CI:  43%|█████▌       | 215/500 [00:01<00:02, 115.22it/s]
bootstrap micro f1 95% CI:  45%|█████▉       | 227/500 [00:01<00:02, 114.63it/s]
bootstrap micro f1 95% CI:  48%|██████▏      | 239/500 [00:02<00:02, 114.68it/s]
bootstrap micro f1 95% CI:  50%|██████▌      | 251/500 [00:02<00:02, 114.92it/s]
bootstrap micro f1 95% CI:  53%|██████▊      | 263/500 [00:02<00:02, 115.01it/s]
bootstrap micro f1 95% CI:  55%|███████▏     | 275/500 [00:02<00:01, 115.11it/s]
bootstrap micro f1 95% CI:  57%|███████▍     | 287/500 [00:02<00:01, 114.70it/s]
bootstrap micro f1 95% CI:  60%|███████▊     | 299/500 [00:02<00:01, 114.76it/s]
bootstrap micro f1 95% CI:  62%|████████     | 311/500 [00:02<00:01, 114.83it/s]
bootstrap micro f1 95% CI:  65%|████████▍    | 323/500 [00:02<00:01, 115.08it/s]
bootstrap micro f1 95% CI:  67%|████████▋    | 335/500 [00:02<00:01, 115.24it/s]
bootstrap micro f1 95% CI:  69%|█████████    | 347/500 [00:03<00:01, 115.37it/s]
bootstrap micro f1 95% CI:  72%|█████████▎   | 359/500 [00:03<00:01, 115.35it/s]
bootstrap micro f1 95% CI:  74%|█████████▋   | 371/500 [00:03<00:01, 115.40it/s]
bootstrap micro f1 95% CI:  77%|█████████▉   | 383/500 [00:03<00:01, 115.35it/s]
bootstrap micro f1 95% CI:  79%|██████████▎  | 395/500 [00:03<00:00, 115.44it/s]
bootstrap micro f1 95% CI:  81%|██████████▌  | 407/500 [00:03<00:00, 114.28it/s]
bootstrap micro f1 95% CI:  84%|██████████▉  | 419/500 [00:03<00:00, 114.33it/s]
bootstrap micro f1 95% CI:  86%|███████████▏ | 431/500 [00:03<00:00, 114.13it/s]
bootstrap micro f1 95% CI:  89%|███████████▌ | 443/500 [00:03<00:00, 113.87it/s]
bootstrap micro f1 95% CI:  91%|███████████▊ | 455/500 [00:03<00:00, 113.94it/s]
bootstrap micro f1 95% CI:  93%|████████████▏| 467/500 [00:04<00:00, 114.02it/s]
bootstrap micro f1 95% CI:  96%|████████████▍| 479/500 [00:04<00:00, 114.46it/s]
bootstrap micro f1 95% CI:  98%|████████████▊| 491/500 [00:04<00:00, 115.43it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:04<00:00, 114.73it/s]


bootstrap macro f1 95% CI:   2%|▎             | 11/500 [00:00<00:04, 105.75it/s]

bootstrap macro f1 95% CI:   5%|▋             | 23/500 [00:00<00:04, 112.37it/s]

bootstrap macro f1 95% CI:   7%|▉             | 35/500 [00:00<00:04, 112.77it/s]

bootstrap macro f1 95% CI:   9%|█▎            | 47/500 [00:00<00:03, 114.34it/s]

bootstrap macro f1 95% CI:  12%|█▋            | 59/500 [00:00<00:03, 115.20it/s]

bootstrap macro f1 95% CI:  14%|█▉            | 71/500 [00:00<00:03, 115.32it/s]

bootstrap macro f1 95% CI:  17%|██▎           | 83/500 [00:00<00:03, 114.89it/s]

bootstrap macro f1 95% CI:  19%|██▋           | 95/500 [00:00<00:03, 115.06it/s]

bootstrap macro f1 95% CI:  21%|██▊          | 107/500 [00:00<00:03, 115.35it/s]

bootstrap macro f1 95% CI:  24%|███          | 119/500 [00:01<00:03, 115.36it/s]

bootstrap macro f1 95% CI:  26%|███▍         | 131/500 [00:01<00:03, 115.36it/s]

bootstrap macro f1 95% CI:  29%|███▋         | 143/500 [00:01<00:03, 115.55it/s]

bootstrap macro f1 95% CI:  31%|████         | 155/500 [00:01<00:02, 115.95it/s]

bootstrap macro f1 95% CI:  33%|████▎        | 167/500 [00:01<00:02, 114.89it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 179/500 [00:01<00:02, 115.13it/s]

bootstrap macro f1 95% CI:  38%|████▉        | 191/500 [00:01<00:02, 115.28it/s]

bootstrap macro f1 95% CI:  41%|█████▎       | 203/500 [00:01<00:02, 114.94it/s]

bootstrap macro f1 95% CI:  43%|█████▌       | 215/500 [00:01<00:02, 115.00it/s]

bootstrap macro f1 95% CI:  45%|█████▉       | 227/500 [00:01<00:02, 114.72it/s]

bootstrap macro f1 95% CI:  48%|██████▏      | 239/500 [00:02<00:02, 114.58it/s]

bootstrap macro f1 95% CI:  50%|██████▌      | 251/500 [00:02<00:02, 114.57it/s]

bootstrap macro f1 95% CI:  53%|██████▊      | 263/500 [00:02<00:02, 114.81it/s]

bootstrap macro f1 95% CI:  55%|███████▏     | 275/500 [00:02<00:01, 114.65it/s]

bootstrap macro f1 95% CI:  57%|███████▍     | 287/500 [00:02<00:01, 113.48it/s]

bootstrap macro f1 95% CI:  60%|███████▊     | 299/500 [00:02<00:01, 113.46it/s]

bootstrap macro f1 95% CI:  62%|████████     | 311/500 [00:02<00:01, 113.45it/s]

bootstrap macro f1 95% CI:  65%|████████▍    | 323/500 [00:02<00:01, 113.13it/s]

bootstrap macro f1 95% CI:  67%|████████▋    | 335/500 [00:02<00:01, 113.48it/s]

bootstrap macro f1 95% CI:  69%|█████████    | 347/500 [00:03<00:01, 113.74it/s]

bootstrap macro f1 95% CI:  72%|█████████▎   | 359/500 [00:03<00:01, 114.24it/s]

bootstrap macro f1 95% CI:  74%|█████████▋   | 371/500 [00:03<00:01, 114.65it/s]

bootstrap macro f1 95% CI:  77%|█████████▉   | 383/500 [00:03<00:01, 114.42it/s]

bootstrap macro f1 95% CI:  79%|██████████▎  | 395/500 [00:03<00:00, 114.32it/s]

bootstrap macro f1 95% CI:  81%|██████████▌  | 407/500 [00:03<00:00, 114.47it/s]

bootstrap macro f1 95% CI:  84%|██████████▉  | 419/500 [00:03<00:00, 113.73it/s]

bootstrap macro f1 95% CI:  86%|███████████▏ | 431/500 [00:03<00:00, 114.08it/s]

bootstrap macro f1 95% CI:  89%|███████████▌ | 443/500 [00:03<00:00, 114.41it/s]

bootstrap macro f1 95% CI:  91%|███████████▊ | 455/500 [00:03<00:00, 114.76it/s]

bootstrap macro f1 95% CI:  93%|████████████▏| 467/500 [00:04<00:00, 115.34it/s]

bootstrap macro f1 95% CI:  96%|████████████▍| 479/500 [00:04<00:00, 115.76it/s]

bootstrap macro f1 95% CI:  98%|████████████▊| 491/500 [00:04<00:00, 115.79it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:04<00:00, 114.42it/s]

bootstrap micro f1 95% CI:   4%|▌             | 20/500 [00:00<00:02, 199.15it/s]
bootstrap micro f1 95% CI:   8%|█▏            | 42/500 [00:00<00:02, 211.15it/s]
bootstrap micro f1 95% CI:  13%|█▊            | 64/500 [00:00<00:02, 214.78it/s]
bootstrap micro f1 95% CI:  17%|██▍           | 86/500 [00:00<00:01, 213.70it/s]
bootstrap micro f1 95% CI:  22%|██▊          | 108/500 [00:00<00:01, 214.78it/s]
bootstrap micro f1 95% CI:  26%|███▍         | 130/500 [00:00<00:01, 216.07it/s]
bootstrap micro f1 95% CI:  30%|███▉         | 152/500 [00:00<00:01, 216.68it/s]
bootstrap micro f1 95% CI:  35%|████▌        | 174/500 [00:00<00:01, 217.45it/s]
bootstrap micro f1 95% CI:  39%|█████        | 196/500 [00:00<00:01, 217.70it/s]
bootstrap micro f1 95% CI:  44%|█████▋       | 218/500 [00:01<00:01, 217.54it/s]
bootstrap micro f1 95% CI:  48%|██████▏      | 240/500 [00:01<00:01, 217.95it/s]
bootstrap micro f1 95% CI:  52%|██████▊      | 262/500 [00:01<00:01, 218.02it/s]
bootstrap micro f1 95% CI:  57%|███████▍     | 284/500 [00:01<00:00, 218.20it/s]
bootstrap micro f1 95% CI:  61%|███████▉     | 306/500 [00:01<00:00, 217.95it/s]
bootstrap micro f1 95% CI:  66%|████████▌    | 328/500 [00:01<00:00, 217.36it/s]
bootstrap micro f1 95% CI:  70%|█████████    | 350/500 [00:01<00:00, 217.73it/s]
bootstrap micro f1 95% CI:  74%|█████████▋   | 372/500 [00:01<00:00, 217.89it/s]
bootstrap micro f1 95% CI:  79%|██████████▏  | 394/500 [00:01<00:00, 217.82it/s]
bootstrap micro f1 95% CI:  83%|██████████▊  | 416/500 [00:01<00:00, 217.74it/s]
bootstrap micro f1 95% CI:  88%|███████████▍ | 438/500 [00:02<00:00, 217.58it/s]
bootstrap micro f1 95% CI:  92%|███████████▉ | 460/500 [00:02<00:00, 217.37it/s]
bootstrap micro f1 95% CI:  96%|████████████▌| 482/500 [00:02<00:00, 217.25it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:02<00:00, 216.74it/s]


bootstrap macro f1 95% CI:   4%|▌             | 21/500 [00:00<00:02, 201.37it/s]

bootstrap macro f1 95% CI:   9%|█▏            | 43/500 [00:00<00:02, 210.58it/s]

bootstrap macro f1 95% CI:  13%|█▊            | 65/500 [00:00<00:02, 213.91it/s]

bootstrap macro f1 95% CI:  17%|██▍           | 87/500 [00:00<00:01, 215.81it/s]

bootstrap macro f1 95% CI:  22%|██▊          | 109/500 [00:00<00:01, 216.95it/s]

bootstrap macro f1 95% CI:  26%|███▍         | 131/500 [00:00<00:01, 217.45it/s]

bootstrap macro f1 95% CI:  31%|███▉         | 153/500 [00:00<00:01, 218.21it/s]

bootstrap macro f1 95% CI:  35%|████▌        | 175/500 [00:00<00:01, 218.45it/s]

bootstrap macro f1 95% CI:  39%|█████        | 197/500 [00:00<00:01, 218.72it/s]

bootstrap macro f1 95% CI:  44%|█████▋       | 219/500 [00:01<00:01, 218.92it/s]

bootstrap macro f1 95% CI:  48%|██████▎      | 241/500 [00:01<00:01, 219.05it/s]

bootstrap macro f1 95% CI:  53%|██████▊      | 263/500 [00:01<00:01, 218.43it/s]

bootstrap macro f1 95% CI:  57%|███████▍     | 285/500 [00:01<00:00, 218.15it/s]

bootstrap macro f1 95% CI:  61%|███████▉     | 307/500 [00:01<00:00, 217.21it/s]

bootstrap macro f1 95% CI:  66%|████████▌    | 329/500 [00:01<00:00, 217.81it/s]

bootstrap macro f1 95% CI:  70%|█████████▏   | 351/500 [00:01<00:00, 217.69it/s]

bootstrap macro f1 95% CI:  75%|█████████▋   | 373/500 [00:01<00:00, 217.38it/s]

bootstrap macro f1 95% CI:  79%|██████████▎  | 395/500 [00:01<00:00, 217.08it/s]

bootstrap macro f1 95% CI:  83%|██████████▊  | 417/500 [00:01<00:00, 216.70it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 439/500 [00:02<00:00, 216.68it/s]

bootstrap macro f1 95% CI:  92%|███████████▉ | 461/500 [00:02<00:00, 217.44it/s]

bootstrap macro f1 95% CI:  97%|████████████▌| 483/500 [00:02<00:00, 217.64it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:02<00:00, 215.51it/s]

bootstrap micro f1 95% CI:   2%|▎             | 11/500 [00:00<00:04, 103.16it/s]
bootstrap micro f1 95% CI:   5%|▋             | 23/500 [00:00<00:04, 107.82it/s]
bootstrap micro f1 95% CI:   7%|▉             | 35/500 [00:00<00:04, 110.51it/s]
bootstrap micro f1 95% CI:   9%|█▎            | 47/500 [00:00<00:04, 111.26it/s]
bootstrap micro f1 95% CI:  12%|█▋            | 59/500 [00:00<00:03, 111.88it/s]
bootstrap micro f1 95% CI:  14%|█▉            | 71/500 [00:00<00:03, 112.32it/s]
bootstrap micro f1 95% CI:  17%|██▎           | 83/500 [00:00<00:03, 112.47it/s]
bootstrap micro f1 95% CI:  19%|██▋           | 95/500 [00:00<00:03, 112.44it/s]
bootstrap micro f1 95% CI:  21%|██▊          | 107/500 [00:00<00:03, 112.21it/s]
bootstrap micro f1 95% CI:  24%|███          | 119/500 [00:01<00:03, 111.97it/s]
bootstrap micro f1 95% CI:  26%|███▍         | 131/500 [00:01<00:03, 111.69it/s]
bootstrap micro f1 95% CI:  29%|███▋         | 143/500 [00:01<00:03, 111.68it/s]
bootstrap micro f1 95% CI:  31%|████         | 155/500 [00:01<00:03, 112.04it/s]
bootstrap micro f1 95% CI:  33%|████▎        | 167/500 [00:01<00:02, 112.39it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 179/500 [00:01<00:02, 112.41it/s]
bootstrap micro f1 95% CI:  38%|████▉        | 191/500 [00:01<00:02, 113.04it/s]
bootstrap micro f1 95% CI:  41%|█████▎       | 203/500 [00:01<00:02, 112.95it/s]
bootstrap micro f1 95% CI:  43%|█████▌       | 215/500 [00:01<00:02, 113.44it/s]
bootstrap micro f1 95% CI:  45%|█████▉       | 227/500 [00:02<00:02, 112.78it/s]
bootstrap micro f1 95% CI:  48%|██████▏      | 239/500 [00:02<00:02, 112.47it/s]
bootstrap micro f1 95% CI:  50%|██████▌      | 251/500 [00:02<00:02, 112.43it/s]
bootstrap micro f1 95% CI:  53%|██████▊      | 263/500 [00:02<00:02, 112.53it/s]
bootstrap micro f1 95% CI:  55%|███████▏     | 275/500 [00:02<00:01, 112.78it/s]
bootstrap micro f1 95% CI:  57%|███████▍     | 287/500 [00:02<00:01, 112.58it/s]
bootstrap micro f1 95% CI:  60%|███████▊     | 299/500 [00:02<00:01, 112.59it/s]
bootstrap micro f1 95% CI:  62%|████████     | 311/500 [00:02<00:01, 112.47it/s]
bootstrap micro f1 95% CI:  65%|████████▍    | 323/500 [00:02<00:01, 112.95it/s]
bootstrap micro f1 95% CI:  67%|████████▋    | 335/500 [00:02<00:01, 112.85it/s]
bootstrap micro f1 95% CI:  69%|█████████    | 347/500 [00:03<00:01, 112.41it/s]
bootstrap micro f1 95% CI:  72%|█████████▎   | 359/500 [00:03<00:01, 112.48it/s]
bootstrap micro f1 95% CI:  74%|█████████▋   | 371/500 [00:03<00:01, 112.53it/s]
bootstrap micro f1 95% CI:  77%|█████████▉   | 383/500 [00:03<00:01, 112.96it/s]
bootstrap micro f1 95% CI:  79%|██████████▎  | 395/500 [00:03<00:00, 112.93it/s]
bootstrap micro f1 95% CI:  81%|██████████▌  | 407/500 [00:03<00:00, 112.69it/s]
bootstrap micro f1 95% CI:  84%|██████████▉  | 419/500 [00:03<00:00, 112.27it/s]
bootstrap micro f1 95% CI:  86%|███████████▏ | 431/500 [00:03<00:00, 111.93it/s]
bootstrap micro f1 95% CI:  89%|███████████▌ | 443/500 [00:03<00:00, 112.10it/s]
bootstrap micro f1 95% CI:  91%|███████████▊ | 455/500 [00:04<00:00, 111.94it/s]
bootstrap micro f1 95% CI:  93%|████████████▏| 467/500 [00:04<00:00, 112.35it/s]
bootstrap micro f1 95% CI:  96%|████████████▍| 479/500 [00:04<00:00, 112.49it/s]
bootstrap micro f1 95% CI:  98%|████████████▊| 491/500 [00:04<00:00, 112.51it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:04<00:00, 112.26it/s]


bootstrap macro f1 95% CI:   2%|▎             | 11/500 [00:00<00:04, 104.29it/s]

bootstrap macro f1 95% CI:   5%|▋             | 23/500 [00:00<00:04, 110.51it/s]

bootstrap macro f1 95% CI:   7%|▉             | 35/500 [00:00<00:04, 111.76it/s]

bootstrap macro f1 95% CI:   9%|█▎            | 47/500 [00:00<00:04, 112.84it/s]

bootstrap macro f1 95% CI:  12%|█▋            | 59/500 [00:00<00:03, 112.63it/s]

bootstrap macro f1 95% CI:  14%|█▉            | 71/500 [00:00<00:03, 111.72it/s]

bootstrap macro f1 95% CI:  17%|██▎           | 83/500 [00:00<00:03, 112.11it/s]

bootstrap macro f1 95% CI:  19%|██▋           | 95/500 [00:00<00:03, 112.30it/s]

bootstrap macro f1 95% CI:  21%|██▊          | 107/500 [00:00<00:03, 112.91it/s]

bootstrap macro f1 95% CI:  24%|███          | 119/500 [00:01<00:03, 113.45it/s]

bootstrap macro f1 95% CI:  26%|███▍         | 131/500 [00:01<00:03, 113.42it/s]

bootstrap macro f1 95% CI:  29%|███▋         | 143/500 [00:01<00:03, 113.32it/s]

bootstrap macro f1 95% CI:  31%|████         | 155/500 [00:01<00:03, 113.28it/s]

bootstrap macro f1 95% CI:  33%|████▎        | 167/500 [00:01<00:02, 113.09it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 179/500 [00:01<00:02, 113.46it/s]

bootstrap macro f1 95% CI:  38%|████▉        | 191/500 [00:01<00:02, 113.29it/s]

bootstrap macro f1 95% CI:  41%|█████▎       | 203/500 [00:01<00:02, 113.05it/s]

bootstrap macro f1 95% CI:  43%|█████▌       | 215/500 [00:01<00:02, 112.64it/s]

bootstrap macro f1 95% CI:  45%|█████▉       | 227/500 [00:02<00:02, 113.07it/s]

bootstrap macro f1 95% CI:  48%|██████▏      | 239/500 [00:02<00:02, 112.71it/s]

bootstrap macro f1 95% CI:  50%|██████▌      | 251/500 [00:02<00:02, 112.36it/s]

bootstrap macro f1 95% CI:  53%|██████▊      | 263/500 [00:02<00:02, 112.15it/s]

bootstrap macro f1 95% CI:  55%|███████▏     | 275/500 [00:02<00:02, 112.25it/s]

bootstrap macro f1 95% CI:  57%|███████▍     | 287/500 [00:02<00:01, 112.81it/s]

bootstrap macro f1 95% CI:  60%|███████▊     | 299/500 [00:02<00:01, 112.74it/s]

bootstrap macro f1 95% CI:  62%|████████     | 311/500 [00:02<00:01, 112.50it/s]

bootstrap macro f1 95% CI:  65%|████████▍    | 323/500 [00:02<00:01, 112.48it/s]

bootstrap macro f1 95% CI:  67%|████████▋    | 335/500 [00:02<00:01, 112.80it/s]

bootstrap macro f1 95% CI:  69%|█████████    | 347/500 [00:03<00:01, 112.36it/s]

bootstrap macro f1 95% CI:  72%|█████████▎   | 359/500 [00:03<00:01, 112.23it/s]

bootstrap macro f1 95% CI:  74%|█████████▋   | 371/500 [00:03<00:01, 112.31it/s]

bootstrap macro f1 95% CI:  77%|█████████▉   | 383/500 [00:03<00:01, 112.06it/s]

bootstrap macro f1 95% CI:  79%|██████████▎  | 395/500 [00:03<00:00, 111.69it/s]

bootstrap macro f1 95% CI:  81%|██████████▌  | 407/500 [00:03<00:00, 111.50it/s]

bootstrap macro f1 95% CI:  84%|██████████▉  | 419/500 [00:03<00:00, 111.07it/s]

bootstrap macro f1 95% CI:  86%|███████████▏ | 431/500 [00:03<00:00, 111.03it/s]

bootstrap macro f1 95% CI:  89%|███████████▌ | 443/500 [00:03<00:00, 111.10it/s]

bootstrap macro f1 95% CI:  91%|███████████▊ | 455/500 [00:04<00:00, 111.09it/s]

bootstrap macro f1 95% CI:  93%|████████████▏| 467/500 [00:04<00:00, 111.33it/s]

bootstrap macro f1 95% CI:  96%|████████████▍| 479/500 [00:04<00:00, 111.76it/s]

bootstrap macro f1 95% CI:  98%|████████████▊| 491/500 [00:04<00:00, 111.12it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:04<00:00, 111.99it/s]

bootstrap micro f1 95% CI:   4%|▌             | 20/500 [00:00<00:02, 193.74it/s]
bootstrap micro f1 95% CI:   8%|█▏            | 42/500 [00:00<00:02, 205.03it/s]
bootstrap micro f1 95% CI:  13%|█▊            | 64/500 [00:00<00:02, 208.84it/s]
bootstrap micro f1 95% CI:  17%|██▍           | 86/500 [00:00<00:01, 210.20it/s]
bootstrap micro f1 95% CI:  22%|██▊          | 108/500 [00:00<00:01, 212.02it/s]
bootstrap micro f1 95% CI:  26%|███▍         | 130/500 [00:00<00:01, 212.92it/s]
bootstrap micro f1 95% CI:  30%|███▉         | 152/500 [00:00<00:01, 213.58it/s]
bootstrap micro f1 95% CI:  35%|████▌        | 174/500 [00:00<00:01, 213.79it/s]
bootstrap micro f1 95% CI:  39%|█████        | 196/500 [00:00<00:01, 214.30it/s]
bootstrap micro f1 95% CI:  44%|█████▋       | 218/500 [00:01<00:01, 214.25it/s]
bootstrap micro f1 95% CI:  48%|██████▏      | 240/500 [00:01<00:01, 213.70it/s]
bootstrap micro f1 95% CI:  52%|██████▊      | 262/500 [00:01<00:01, 213.25it/s]
bootstrap micro f1 95% CI:  57%|███████▍     | 284/500 [00:01<00:01, 211.80it/s]
bootstrap micro f1 95% CI:  61%|███████▉     | 306/500 [00:01<00:00, 212.00it/s]
bootstrap micro f1 95% CI:  66%|████████▌    | 328/500 [00:01<00:00, 212.11it/s]
bootstrap micro f1 95% CI:  70%|█████████    | 350/500 [00:01<00:00, 212.48it/s]
bootstrap micro f1 95% CI:  74%|█████████▋   | 372/500 [00:01<00:00, 213.23it/s]
bootstrap micro f1 95% CI:  79%|██████████▏  | 394/500 [00:01<00:00, 213.49it/s]
bootstrap micro f1 95% CI:  83%|██████████▊  | 416/500 [00:01<00:00, 214.22it/s]
bootstrap micro f1 95% CI:  88%|███████████▍ | 438/500 [00:02<00:00, 213.90it/s]
bootstrap micro f1 95% CI:  92%|███████████▉ | 460/500 [00:02<00:00, 214.21it/s]
bootstrap micro f1 95% CI:  96%|████████████▌| 482/500 [00:02<00:00, 214.35it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:02<00:00, 212.59it/s]


bootstrap macro f1 95% CI:   4%|▌             | 20/500 [00:00<00:02, 197.19it/s]


In [84]:
!python ../llava/eval/rrg_eval/run.py ../results/llavarad/gender_f.jsonl --run_name gender_f

[2025-07-03 21:03:20,671] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CheXbert:   0%|                                           | 0/5 [00:00<?, ?it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

bootstrap micro f1 95% CI:   0%|                        | 0/500 [00:00<?, ?it/s]
bootstrap micro f1 95% CI:   3%|▎             | 13/500 [00:00<00:03, 122.59it/s]
bootstrap micro f1 95% CI:   6%|▊             | 28/500 [00:00<00:03, 133.12it/s]
bootstrap micro f1 95% CI:   9%|█▏            | 43/500 [00:00<00:03, 136.64it/s]
bootstrap micro f1 95% CI:  12%|█▌            | 58/500 [00:00<00:03, 138.48it/s]
bootstrap micro f1 95% CI:  15%|██            | 73/500 [00:00<00:03, 139.77it/s]
bootstrap micro f1 95% CI:  18%|██▍           | 88/500 [00:00<00:02, 140.14it/s]
bootstrap micro f1 95% CI:  21%|██▋          | 103/500 [00:00<00:02, 140.42it/s]
bootstrap micro f1 95% CI:  24%|███          | 118/500 [00:00<00:02, 140.59it/s]
bootstrap micro f1 95% CI:  27%|███▍         | 133/500 [00:00<00:02, 140.93it/s]
bootstrap micro f1 95% CI:  30%|███▊         | 148/500 [00:01<00:02, 141.19it/s]
bootstrap micro f1 95% CI:  33%|████▏        | 163/500 [00:01<00:02, 141.34it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 178/500 [00:01<00:02, 141.40it/s]
bootstrap micro f1 95% CI:  39%|█████        | 193/500 [00:01<00:02, 141.38it/s]
bootstrap micro f1 95% CI:  42%|█████▍       | 208/500 [00:01<00:02, 141.75it/s]
bootstrap micro f1 95% CI:  45%|█████▊       | 223/500 [00:01<00:01, 141.69it/s]
bootstrap micro f1 95% CI:  48%|██████▏      | 238/500 [00:01<00:01, 141.35it/s]
bootstrap micro f1 95% CI:  51%|██████▌      | 253/500 [00:01<00:01, 141.48it/s]
bootstrap micro f1 95% CI:  54%|██████▉      | 268/500 [00:01<00:01, 141.44it/s]
bootstrap micro f1 95% CI:  57%|███████▎     | 283/500 [00:02<00:01, 141.62it/s]
bootstrap micro f1 95% CI:  60%|███████▋     | 298/500 [00:02<00:01, 142.00it/s]
bootstrap micro f1 95% CI:  63%|████████▏    | 313/500 [00:02<00:01, 141.83it/s]
bootstrap micro f1 95% CI:  66%|████████▌    | 328/500 [00:02<00:01, 141.59it/s]
bootstrap micro f1 95% CI:  69%|████████▉    | 343/500 [00:02<00:01, 141.41it/s]
bootstrap micro f1 95% CI:  72%|█████████▎   | 358/500 [00:02<00:01, 141.29it/s]
bootstrap micro f1 95% CI:  75%|█████████▋   | 373/500 [00:02<00:00, 141.35it/s]
bootstrap micro f1 95% CI:  78%|██████████   | 388/500 [00:02<00:00, 139.67it/s]
bootstrap micro f1 95% CI:  81%|██████████▍  | 403/500 [00:02<00:00, 140.05it/s]
bootstrap micro f1 95% CI:  84%|██████████▊  | 418/500 [00:02<00:00, 140.53it/s]
bootstrap micro f1 95% CI:  87%|███████████▎ | 433/500 [00:03<00:00, 140.55it/s]
bootstrap micro f1 95% CI:  90%|███████████▋ | 448/500 [00:03<00:00, 140.54it/s]
bootstrap micro f1 95% CI:  93%|████████████ | 463/500 [00:03<00:00, 140.51it/s]
bootstrap micro f1 95% CI:  96%|████████████▍| 478/500 [00:03<00:00, 140.82it/s]
bootstrap micro f1 95% CI:  99%|████████████▊| 493/500 [00:03<00:00, 141.29it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 140.51it/s]


bootstrap macro f1 95% CI:   3%|▎             | 13/500 [00:00<00:03, 127.26it/s]

bootstrap macro f1 95% CI:   6%|▊             | 28/500 [00:00<00:03, 136.74it/s]

bootstrap macro f1 95% CI:   9%|█▏            | 43/500 [00:00<00:03, 139.39it/s]

bootstrap macro f1 95% CI:  12%|█▌            | 58/500 [00:00<00:03, 140.49it/s]

bootstrap macro f1 95% CI:  15%|██            | 73/500 [00:00<00:03, 141.82it/s]

bootstrap macro f1 95% CI:  18%|██▍           | 88/500 [00:00<00:02, 142.28it/s]

bootstrap macro f1 95% CI:  21%|██▋          | 103/500 [00:00<00:02, 142.32it/s]

bootstrap macro f1 95% CI:  24%|███          | 118/500 [00:00<00:02, 142.19it/s]

bootstrap macro f1 95% CI:  27%|███▍         | 133/500 [00:00<00:02, 142.28it/s]

bootstrap macro f1 95% CI:  30%|███▊         | 148/500 [00:01<00:02, 142.40it/s]

bootstrap macro f1 95% CI:  33%|████▏        | 163/500 [00:01<00:02, 142.20it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 178/500 [00:01<00:02, 142.35it/s]

bootstrap macro f1 95% CI:  39%|█████        | 193/500 [00:01<00:02, 142.27it/s]

bootstrap macro f1 95% CI:  42%|█████▍       | 208/500 [00:01<00:02, 142.14it/s]

bootstrap macro f1 95% CI:  45%|█████▊       | 223/500 [00:01<00:01, 142.05it/s]

bootstrap macro f1 95% CI:  48%|██████▏      | 238/500 [00:01<00:01, 140.53it/s]

bootstrap macro f1 95% CI:  51%|██████▌      | 253/500 [00:01<00:01, 140.71it/s]

bootstrap macro f1 95% CI:  54%|██████▉      | 268/500 [00:01<00:01, 140.90it/s]

bootstrap macro f1 95% CI:  57%|███████▎     | 283/500 [00:02<00:01, 141.20it/s]

bootstrap macro f1 95% CI:  60%|███████▋     | 298/500 [00:02<00:01, 141.47it/s]

bootstrap macro f1 95% CI:  63%|████████▏    | 313/500 [00:02<00:01, 141.82it/s]

bootstrap macro f1 95% CI:  66%|████████▌    | 328/500 [00:02<00:01, 142.25it/s]

bootstrap macro f1 95% CI:  69%|████████▉    | 343/500 [00:02<00:01, 142.07it/s]

bootstrap macro f1 95% CI:  72%|█████████▎   | 358/500 [00:02<00:01, 141.54it/s]

bootstrap macro f1 95% CI:  75%|█████████▋   | 373/500 [00:02<00:00, 141.46it/s]

bootstrap macro f1 95% CI:  78%|██████████   | 388/500 [00:02<00:00, 141.73it/s]

bootstrap macro f1 95% CI:  81%|██████████▍  | 403/500 [00:02<00:00, 141.45it/s]

bootstrap macro f1 95% CI:  84%|██████████▊  | 418/500 [00:02<00:00, 141.62it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


bootstrap macro f1 95% CI:  87%|███████████▎ | 433/500 [00:03<00:00, 128.44it/s]

bootstrap macro f1 95% CI:  89%|███████████▌ | 447/500 [00:03<00:00, 131.01it/s]

bootstrap macro f1 95% CI:  92%|████████████ | 462/500 [00:03<00:00, 133.92it/s]

bootstrap macro f1 95% CI:  95%|████████████▍| 477/500 [00:03<00:00, 136.07it/s]

bootstrap macro f1 95% CI:  98%|████████████▊| 492/500 [00:03<00:00, 137.73it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 139.63it/s]

bootstrap micro f1 95% CI:   5%|▋             | 24/500 [00:00<00:02, 231.14it/s]
bootstrap micro f1 95% CI:  10%|█▍            | 50/500 [00:00<00:01, 247.28it/s]
bootstrap micro f1 95% CI:  15%|██▏           | 77/500 [00:00<00:01, 253.57it/s]
bootstrap micro f1 95% CI:  21%|██▋          | 104/500 [00:00<00:01, 256.23it/s]
bootstrap micro f1 95% CI:  26%|███▍         | 130/500 [00:00<00:01, 256.86it/s]
bootstrap micro f1 95% CI:  31%|████         | 156/500 [00:00<00:01, 257.17it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 182/500 [00:00<00:01, 258.01it/s]
bootstrap micro f1 95% CI:  42%|█████▍       | 208/500 [00:00<00:01, 258.12it/s]
bootstrap micro f1 95% CI:  47%|██████       | 234/500 [00:00<00:01, 258.31it/s]
bootstrap micro f1 95% CI:  52%|██████▊      | 260/500 [00:01<00:00, 258.35it/s]
bootstrap micro f1 95% CI:  57%|███████▍     | 286/500 [00:01<00:00, 258.50it/s]
bootstrap micro f1 95% CI:  62%|████████     | 312/500 [00:01<00:00, 257.02it/s]
bootstrap micro f1 95% CI:  68%|████████▊    | 338/500 [00:01<00:00, 257.38it/s]
bootstrap micro f1 95% CI:  73%|█████████▍   | 364/500 [00:01<00:00, 257.77it/s]
bootstrap micro f1 95% CI:  78%|██████████▏  | 390/500 [00:01<00:00, 257.83it/s]
bootstrap micro f1 95% CI:  83%|██████████▊  | 416/500 [00:01<00:00, 257.96it/s]
bootstrap micro f1 95% CI:  88%|███████████▍ | 442/500 [00:01<00:00, 258.40it/s]
bootstrap micro f1 95% CI:  94%|████████████▏| 468/500 [00:01<00:00, 258.30it/s]
bootstrap micro f1 95% CI:  99%|████████████▊| 494/500 [00:01<00:00, 258.37it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 256.95it/s]


bootstrap macro f1 95% CI:   5%|▋             | 24/500 [00:00<00:02, 237.03it/s]

bootstrap macro f1 95% CI:  10%|█▍            | 50/500 [00:00<00:01, 250.12it/s]

bootstrap macro f1 95% CI:  15%|██▏           | 76/500 [00:00<00:01, 253.84it/s]

bootstrap macro f1 95% CI:  20%|██▋          | 102/500 [00:00<00:01, 252.44it/s]

bootstrap macro f1 95% CI:  26%|███▎         | 129/500 [00:00<00:01, 255.24it/s]

bootstrap macro f1 95% CI:  31%|████         | 156/500 [00:00<00:01, 256.91it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 182/500 [00:00<00:01, 257.77it/s]

bootstrap macro f1 95% CI:  42%|█████▍       | 208/500 [00:00<00:01, 258.35it/s]

bootstrap macro f1 95% CI:  47%|██████       | 234/500 [00:00<00:01, 258.76it/s]

bootstrap macro f1 95% CI:  52%|██████▊      | 260/500 [00:01<00:00, 258.93it/s]

bootstrap macro f1 95% CI:  57%|███████▍     | 286/500 [00:01<00:00, 259.16it/s]

bootstrap macro f1 95% CI:  62%|████████     | 312/500 [00:01<00:00, 259.40it/s]

bootstrap macro f1 95% CI:  68%|████████▊    | 338/500 [00:01<00:00, 259.49it/s]

bootstrap macro f1 95% CI:  73%|█████████▍   | 364/500 [00:01<00:00, 259.09it/s]

bootstrap macro f1 95% CI:  78%|██████████▏  | 390/500 [00:01<00:00, 256.32it/s]

bootstrap macro f1 95% CI:  83%|██████████▊  | 416/500 [00:01<00:00, 257.23it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 442/500 [00:01<00:00, 257.84it/s]

bootstrap macro f1 95% CI:  94%|████████████▏| 468/500 [00:01<00:00, 258.35it/s]

bootstrap macro f1 95% CI:  99%|████████████▊| 494/500 [00:01<00:00, 258.24it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 255.36it/s]

bootstrap micro f1 95% CI:   3%|▎             | 13/500 [00:00<00:03, 127.36it/s]
bootstrap micro f1 95% CI:   5%|▊             | 27/500 [00:00<00:03, 134.62it/s]
bootstrap micro f1 95% CI:   8%|█▏            | 41/500 [00:00<00:03, 136.66it/s]
bootstrap micro f1 95% CI:  11%|█▌            | 55/500 [00:00<00:03, 137.57it/s]
bootstrap micro f1 95% CI:  14%|█▉            | 69/500 [00:00<00:03, 137.56it/s]
bootstrap micro f1 95% CI:  17%|██▎           | 83/500 [00:00<00:03, 136.29it/s]
bootstrap micro f1 95% CI:  19%|██▋           | 97/500 [00:00<00:02, 137.39it/s]
bootstrap micro f1 95% CI:  22%|██▉          | 111/500 [00:00<00:02, 137.73it/s]
bootstrap micro f1 95% CI:  25%|███▎         | 125/500 [00:00<00:02, 137.97it/s]
bootstrap micro f1 95% CI:  28%|███▌         | 139/500 [00:01<00:02, 138.30it/s]
bootstrap micro f1 95% CI:  31%|███▉         | 153/500 [00:01<00:02, 138.36it/s]
bootstrap micro f1 95% CI:  33%|████▎        | 167/500 [00:01<00:02, 138.41it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 181/500 [00:01<00:02, 138.46it/s]
bootstrap micro f1 95% CI:  39%|█████        | 195/500 [00:01<00:02, 138.43it/s]
bootstrap micro f1 95% CI:  42%|█████▍       | 209/500 [00:01<00:02, 138.79it/s]
bootstrap micro f1 95% CI:  45%|█████▊       | 223/500 [00:01<00:02, 138.46it/s]
bootstrap micro f1 95% CI:  47%|██████▏      | 237/500 [00:01<00:01, 137.28it/s]
bootstrap micro f1 95% CI:  50%|██████▌      | 251/500 [00:01<00:01, 137.67it/s]
bootstrap micro f1 95% CI:  53%|██████▉      | 265/500 [00:01<00:01, 137.99it/s]
bootstrap micro f1 95% CI:  56%|███████▎     | 279/500 [00:02<00:01, 138.59it/s]
bootstrap micro f1 95% CI:  59%|███████▌     | 293/500 [00:02<00:01, 138.96it/s]
bootstrap micro f1 95% CI:  61%|███████▉     | 307/500 [00:02<00:01, 139.04it/s]
bootstrap micro f1 95% CI:  64%|████████▎    | 321/500 [00:02<00:01, 139.24it/s]
bootstrap micro f1 95% CI:  67%|████████▋    | 336/500 [00:02<00:01, 139.59it/s]
bootstrap micro f1 95% CI:  70%|█████████    | 350/500 [00:02<00:01, 139.33it/s]
bootstrap micro f1 95% CI:  73%|█████████▍   | 364/500 [00:02<00:00, 139.33it/s]
bootstrap micro f1 95% CI:  76%|█████████▊   | 378/500 [00:02<00:00, 139.33it/s]
bootstrap micro f1 95% CI:  78%|██████████▏  | 392/500 [00:02<00:00, 139.33it/s]
bootstrap micro f1 95% CI:  81%|██████████▌  | 406/500 [00:02<00:00, 139.46it/s]
bootstrap micro f1 95% CI:  84%|██████████▉  | 420/500 [00:03<00:00, 139.38it/s]
bootstrap micro f1 95% CI:  87%|███████████▎ | 434/500 [00:03<00:00, 138.97it/s]
bootstrap micro f1 95% CI:  90%|███████████▋ | 448/500 [00:03<00:00, 138.75it/s]
bootstrap micro f1 95% CI:  92%|████████████ | 462/500 [00:03<00:00, 138.71it/s]
bootstrap micro f1 95% CI:  95%|████████████▍| 476/500 [00:03<00:00, 138.58it/s]
bootstrap micro f1 95% CI:  98%|████████████▋| 490/500 [00:03<00:00, 138.52it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 138.32it/s]


bootstrap macro f1 95% CI:   3%|▎             | 13/500 [00:00<00:03, 126.79it/s]

bootstrap macro f1 95% CI:   6%|▊             | 28/500 [00:00<00:03, 134.70it/s]

bootstrap macro f1 95% CI:   8%|█▏            | 42/500 [00:00<00:03, 136.96it/s]

bootstrap macro f1 95% CI:  11%|█▌            | 56/500 [00:00<00:03, 137.86it/s]

bootstrap macro f1 95% CI:  14%|█▉            | 71/500 [00:00<00:03, 138.79it/s]

bootstrap macro f1 95% CI:  17%|██▍           | 86/500 [00:00<00:02, 139.59it/s]

bootstrap macro f1 95% CI:  20%|██▌          | 100/500 [00:00<00:02, 139.67it/s]

bootstrap macro f1 95% CI:  23%|██▉          | 114/500 [00:00<00:02, 139.53it/s]

bootstrap macro f1 95% CI:  26%|███▎         | 128/500 [00:00<00:02, 139.27it/s]

bootstrap macro f1 95% CI:  28%|███▋         | 142/500 [00:01<00:02, 138.84it/s]

bootstrap macro f1 95% CI:  31%|████         | 156/500 [00:01<00:02, 138.91it/s]

bootstrap macro f1 95% CI:  34%|████▍        | 171/500 [00:01<00:02, 139.40it/s]

bootstrap macro f1 95% CI:  37%|████▊        | 186/500 [00:01<00:02, 139.71it/s]

bootstrap macro f1 95% CI:  40%|█████▏       | 200/500 [00:01<00:02, 138.70it/s]

bootstrap macro f1 95% CI:  43%|█████▌       | 214/500 [00:01<00:02, 138.85it/s]

bootstrap macro f1 95% CI:  46%|█████▉       | 228/500 [00:01<00:01, 138.94it/s]

bootstrap macro f1 95% CI:  48%|██████▎      | 242/500 [00:01<00:01, 139.03it/s]

bootstrap macro f1 95% CI:  51%|██████▋      | 256/500 [00:01<00:01, 139.11it/s]

bootstrap macro f1 95% CI:  54%|███████      | 270/500 [00:01<00:01, 139.15it/s]

bootstrap macro f1 95% CI:  57%|███████▍     | 284/500 [00:02<00:01, 139.26it/s]

bootstrap macro f1 95% CI:  60%|███████▋     | 298/500 [00:02<00:01, 139.13it/s]

bootstrap macro f1 95% CI:  62%|████████     | 312/500 [00:02<00:01, 139.03it/s]

bootstrap macro f1 95% CI:  65%|████████▍    | 326/500 [00:02<00:01, 139.14it/s]

bootstrap macro f1 95% CI:  68%|████████▊    | 340/500 [00:02<00:01, 139.16it/s]

bootstrap macro f1 95% CI:  71%|█████████▏   | 354/500 [00:02<00:01, 139.12it/s]

bootstrap macro f1 95% CI:  74%|█████████▌   | 368/500 [00:02<00:00, 139.37it/s]

bootstrap macro f1 95% CI:  76%|█████████▉   | 382/500 [00:02<00:00, 139.42it/s]

bootstrap macro f1 95% CI:  79%|██████████▎  | 396/500 [00:02<00:00, 139.46it/s]

bootstrap macro f1 95% CI:  82%|██████████▋  | 410/500 [00:02<00:00, 139.24it/s]

bootstrap macro f1 95% CI:  85%|███████████  | 424/500 [00:03<00:00, 138.76it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 438/500 [00:03<00:00, 138.38it/s]

bootstrap macro f1 95% CI:  90%|███████████▊ | 452/500 [00:03<00:00, 138.51it/s]

bootstrap macro f1 95% CI:  93%|████████████ | 466/500 [00:03<00:00, 138.88it/s]

bootstrap macro f1 95% CI:  96%|████████████▍| 480/500 [00:03<00:00, 138.69it/s]

bootstrap macro f1 95% CI:  99%|████████████▊| 494/500 [00:03<00:00, 138.60it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 138.55it/s]

bootstrap micro f1 95% CI:   5%|▋             | 23/500 [00:00<00:02, 228.24it/s]
bootstrap micro f1 95% CI:  10%|█▎            | 49/500 [00:00<00:01, 244.10it/s]
bootstrap micro f1 95% CI:  15%|██            | 75/500 [00:00<00:01, 248.31it/s]
bootstrap micro f1 95% CI:  20%|██▋          | 101/500 [00:00<00:01, 249.38it/s]
bootstrap micro f1 95% CI:  25%|███▎         | 127/500 [00:00<00:01, 249.87it/s]
bootstrap micro f1 95% CI:  31%|███▉         | 153/500 [00:00<00:01, 250.83it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 179/500 [00:00<00:01, 252.41it/s]
bootstrap micro f1 95% CI:  41%|█████▎       | 205/500 [00:00<00:01, 253.28it/s]
bootstrap micro f1 95% CI:  46%|██████       | 231/500 [00:00<00:01, 253.46it/s]
bootstrap micro f1 95% CI:  51%|██████▋      | 257/500 [00:01<00:00, 254.12it/s]
bootstrap micro f1 95% CI:  57%|███████▎     | 283/500 [00:01<00:00, 254.06it/s]
bootstrap micro f1 95% CI:  62%|████████     | 309/500 [00:01<00:00, 254.24it/s]
bootstrap micro f1 95% CI:  67%|████████▋    | 335/500 [00:01<00:00, 254.19it/s]
bootstrap micro f1 95% CI:  72%|█████████▍   | 361/500 [00:01<00:00, 254.42it/s]
bootstrap micro f1 95% CI:  77%|██████████   | 387/500 [00:01<00:00, 252.66it/s]
bootstrap micro f1 95% CI:  83%|██████████▋  | 413/500 [00:01<00:00, 253.00it/s]
bootstrap micro f1 95% CI:  88%|███████████▍ | 439/500 [00:01<00:00, 253.12it/s]
bootstrap micro f1 95% CI:  93%|████████████ | 465/500 [00:01<00:00, 253.60it/s]
bootstrap micro f1 95% CI:  98%|████████████▊| 491/500 [00:01<00:00, 253.93it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 252.34it/s]


bootstrap macro f1 95% CI:   5%|▋             | 24/500 [00:00<00:02, 233.71it/s]

bootstrap macro f1 95% CI:  10%|█▍            | 50/500 [00:00<00:01, 246.60it/s]

bootstrap macro f1 95% CI:  15%|██▏           | 76/500 [00:00<00:01, 251.07it/s]

bootstrap macro f1 95% CI:  20%|██▋          | 102/500 [00:00<00:01, 252.75it/s]

bootstrap macro f1 95% CI:  26%|███▎         | 128/500 [00:00<00:01, 253.83it/s]

bootstrap macro f1 95% CI:  31%|████         | 154/500 [00:00<00:01, 253.25it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 180/500 [00:00<00:01, 253.93it/s]

bootstrap macro f1 95% CI:  41%|█████▎       | 206/500 [00:00<00:01, 254.06it/s]

bootstrap macro f1 95% CI:  46%|██████       | 232/500 [00:00<00:01, 254.60it/s]

bootstrap macro f1 95% CI:  52%|██████▋      | 258/500 [00:01<00:00, 254.67it/s]

bootstrap macro f1 95% CI:  57%|███████▍     | 284/500 [00:01<00:00, 254.83it/s]

bootstrap macro f1 95% CI:  62%|████████     | 310/500 [00:01<00:00, 254.40it/s]

bootstrap macro f1 95% CI:  67%|████████▋    | 336/500 [00:01<00:00, 254.43it/s]

bootstrap macro f1 95% CI:  72%|█████████▍   | 362/500 [00:01<00:00, 254.05it/s]

bootstrap macro f1 95% CI:  78%|██████████   | 388/500 [00:01<00:00, 253.23it/s]

bootstrap macro f1 95% CI:  83%|██████████▊  | 414/500 [00:01<00:00, 252.88it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 440/500 [00:01<00:00, 253.59it/s]

bootstrap macro f1 95% CI:  93%|████████████ | 466/500 [00:01<00:00, 254.22it/s]

F1-RadGraph:  20%|██████▍                         | 1/5 [00:33<02:15, 33.79s/it]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
ROUGE-L: 100%|████████████████████████████████████| 5/5 [01:17<00:00, 15.56s/it]


Total reports: 1031

========== Main Results ==========
        Micro-F1-14  Micro-F1-5  Macro-F1-14  ...     BLEU-1     BLEU-4   ROUGE-L
median     0.590721    0.606333     0.397536  ...  38.206831  15.487343  0.309403
ci_l       0.572845    0.583516     0.365758  ...  37.081520  14.577350  0.301111
ci_h       0.607003    0.626909     0.427270  ...  39.273923  16.350068  0.317938

[3 rows x 12 columns]

wandb: Currently logged in as: mbhosale (bhosalems_) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.20.1
wandb: Run data is saved locally in /home/csgrad/mbhosale/phd/MrFair/LLaVA-Rad/scripts/wandb/run-20250703_210441-5p8i38nw
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run gender_f

#### 2. Age Groups

In [85]:
!python ../llava/eval/rrg_eval/run.py ../results/llavarad/age_0_44.jsonl --run_name age_0_44

[2025-07-03 21:10:06,605] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CheXbert:   0%|                                           | 0/5 [00:00<?, ?it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

bootstrap micro f1 95% CI:   0%|                        | 0/500 [00:00<?, ?it/s]
bootstrap micro f1 95% CI:  14%|█▉            | 71/500 [00:00<00:00, 706.45it/s]
bootstrap micro f1 95% CI:  28%|███▋         | 142/500 [00:00<00:00, 707.35it/s]
bootstrap micro f1 95% CI:  43%|█████▌       | 215/500 [00:00<00:00, 714.02it/s]
bootstrap micro f1 95% CI:  58%|███████▍     | 288/500 [00:00<00:00, 717.41it/s]
bootstrap micro f1 95% CI:  72%|█████████▍   | 361/500 [00:00<00:00, 719.21it/s]
bootstrap micro f1 95% CI:  87%|███████████▎ | 434/500 [00:00<00:00, 721.24it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:00<00:00, 717.86it/s]
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [86]:
!python ../llava/eval/rrg_eval/run.py ../results/llavarad/age_44_65.jsonl --run_name age_44_65

[2025-07-03 21:10:47,720] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CheXbert:   0%|                                           | 0/5 [00:00<?, ?it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

bootstrap micro f1 95% CI:   0%|                        | 0/500 [00:00<?, ?it/s]
bootstrap micro f1 95% CI:   3%|▎             | 13/500 [00:00<00:04, 121.18it/s]
bootstrap micro f1 95% CI:   5%|▊             | 27/500 [00:00<00:03, 129.88it/s]
bootstrap micro f1 95% CI:   8%|█▏            | 41/500 [00:00<00:03, 132.88it/s]
bootstrap micro f1 95% CI:  11%|█▌            | 55/500 [00:00<00:03, 134.42it/s]
bootstrap micro f1 95% CI:  14%|█▉            | 69/500 [00:00<00:03, 135.40it/s]
bootstrap micro f1 95% CI:  17%|██▎           | 83/500 [00:00<00:03, 135.76it/s]
bootstrap micro f1 95% CI:  19%|██▋           | 97/500 [00:00<00:02, 136.07it/s]
bootstrap micro f1 95% CI:  22%|██▉          | 111/500 [00:00<00:02, 136.44it/s]
bootstrap micro f1 95% CI:  25%|███▎         | 125/500 [00:00<00:02, 136.51it/s]
bootstrap micro f1 95% CI:  28%|███▌         | 139/500 [00:01<00:02, 136.55it/s]
bootstrap micro f1 95% CI:  31%|███▉         | 153/500 [00:01<00:02, 136.68it/s]
bootstrap micro f1 95% CI:  33%|████▎        | 167/500 [00:01<00:02, 136.60it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 181/500 [00:01<00:02, 136.57it/s]
bootstrap micro f1 95% CI:  39%|█████        | 195/500 [00:01<00:02, 136.69it/s]
bootstrap micro f1 95% CI:  42%|█████▍       | 209/500 [00:01<00:02, 136.79it/s]
bootstrap micro f1 95% CI:  45%|█████▊       | 223/500 [00:01<00:02, 137.04it/s]
bootstrap micro f1 95% CI:  47%|██████▏      | 237/500 [00:01<00:01, 136.88it/s]
bootstrap micro f1 95% CI:  50%|██████▌      | 251/500 [00:01<00:01, 136.75it/s]
bootstrap micro f1 95% CI:  53%|██████▉      | 265/500 [00:01<00:01, 136.83it/s]
bootstrap micro f1 95% CI:  56%|███████▎     | 279/500 [00:02<00:01, 136.75it/s]
bootstrap micro f1 95% CI:  59%|███████▌     | 293/500 [00:02<00:01, 136.69it/s]
bootstrap micro f1 95% CI:  61%|███████▉     | 307/500 [00:02<00:01, 136.70it/s]
bootstrap micro f1 95% CI:  64%|████████▎    | 321/500 [00:02<00:01, 135.41it/s]
bootstrap micro f1 95% CI:  67%|████████▋    | 335/500 [00:02<00:01, 135.87it/s]
bootstrap micro f1 95% CI:  70%|█████████    | 349/500 [00:02<00:01, 136.26it/s]
bootstrap micro f1 95% CI:  73%|█████████▍   | 363/500 [00:02<00:01, 136.49it/s]
bootstrap micro f1 95% CI:  75%|█████████▊   | 377/500 [00:02<00:00, 136.78it/s]
bootstrap micro f1 95% CI:  78%|██████████▏  | 391/500 [00:02<00:00, 136.93it/s]
bootstrap micro f1 95% CI:  81%|██████████▌  | 405/500 [00:02<00:00, 136.91it/s]
bootstrap micro f1 95% CI:  84%|██████████▉  | 419/500 [00:03<00:00, 137.10it/s]
bootstrap micro f1 95% CI:  87%|███████████▎ | 433/500 [00:03<00:00, 137.09it/s]
bootstrap micro f1 95% CI:  89%|███████████▌ | 447/500 [00:03<00:00, 137.33it/s]
bootstrap micro f1 95% CI:  92%|███████████▉ | 461/500 [00:03<00:00, 137.29it/s]
bootstrap micro f1 95% CI:  95%|████████████▎| 475/500 [00:03<00:00, 135.64it/s]
bootstrap micro f1 95% CI:  98%|████████████▋| 489/500 [00:03<00:00, 136.13it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 136.16it/s]


bootstrap macro f1 95% CI:   3%|▎             | 13/500 [00:00<00:03, 124.45it/s]

bootstrap macro f1 95% CI:   5%|▊             | 27/500 [00:00<00:03, 131.76it/s]

bootstrap macro f1 95% CI:   8%|█▏            | 41/500 [00:00<00:03, 134.21it/s]

bootstrap macro f1 95% CI:  11%|█▌            | 55/500 [00:00<00:03, 135.30it/s]

bootstrap macro f1 95% CI:  14%|█▉            | 69/500 [00:00<00:03, 135.72it/s]

bootstrap macro f1 95% CI:  17%|██▎           | 83/500 [00:00<00:03, 135.94it/s]

bootstrap macro f1 95% CI:  19%|██▋           | 97/500 [00:00<00:02, 136.22it/s]

bootstrap macro f1 95% CI:  22%|██▉          | 111/500 [00:00<00:02, 136.37it/s]

bootstrap macro f1 95% CI:  25%|███▎         | 125/500 [00:00<00:02, 134.91it/s]

bootstrap macro f1 95% CI:  28%|███▌         | 139/500 [00:01<00:02, 135.66it/s]

bootstrap macro f1 95% CI:  31%|███▉         | 153/500 [00:01<00:02, 135.87it/s]

bootstrap macro f1 95% CI:  33%|████▎        | 167/500 [00:01<00:02, 136.32it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 181/500 [00:01<00:02, 136.47it/s]

bootstrap macro f1 95% CI:  39%|█████        | 195/500 [00:01<00:02, 136.52it/s]

bootstrap macro f1 95% CI:  42%|█████▍       | 209/500 [00:01<00:02, 136.68it/s]

bootstrap macro f1 95% CI:  45%|█████▊       | 223/500 [00:01<00:02, 136.94it/s]

bootstrap macro f1 95% CI:  47%|██████▏      | 237/500 [00:01<00:01, 136.91it/s]

bootstrap macro f1 95% CI:  50%|██████▌      | 251/500 [00:01<00:01, 136.99it/s]

bootstrap macro f1 95% CI:  53%|██████▉      | 265/500 [00:01<00:01, 137.26it/s]

bootstrap macro f1 95% CI:  56%|███████▎     | 279/500 [00:02<00:01, 137.31it/s]

bootstrap macro f1 95% CI:  59%|███████▌     | 293/500 [00:02<00:01, 135.92it/s]

bootstrap macro f1 95% CI:  61%|███████▉     | 307/500 [00:02<00:01, 136.24it/s]

bootstrap macro f1 95% CI:  64%|████████▎    | 321/500 [00:02<00:01, 136.48it/s]

bootstrap macro f1 95% CI:  67%|████████▋    | 335/500 [00:02<00:01, 136.79it/s]

bootstrap macro f1 95% CI:  70%|█████████    | 349/500 [00:02<00:01, 136.87it/s]

bootstrap macro f1 95% CI:  73%|█████████▍   | 363/500 [00:02<00:01, 136.92it/s]

bootstrap macro f1 95% CI:  75%|█████████▊   | 377/500 [00:02<00:00, 137.15it/s]

bootstrap macro f1 95% CI:  78%|██████████▏  | 391/500 [00:02<00:00, 137.36it/s]

bootstrap macro f1 95% CI:  81%|██████████▌  | 405/500 [00:02<00:00, 137.28it/s]

bootstrap macro f1 95% CI:  84%|██████████▉  | 419/500 [00:03<00:00, 137.39it/s]

bootstrap macro f1 95% CI:  87%|███████████▎ | 433/500 [00:03<00:00, 137.42it/s]

bootstrap macro f1 95% CI:  89%|███████████▌ | 447/500 [00:03<00:00, 136.09it/s]

bootstrap macro f1 95% CI:  92%|███████████▉ | 461/500 [00:03<00:00, 136.45it/s]

bootstrap macro f1 95% CI:  95%|████████████▎| 475/500 [00:03<00:00, 136.59it/s]

bootstrap macro f1 95% CI:  98%|████████████▋| 489/500 [00:03<00:00, 136.76it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 136.11it/s]

bootstrap micro f1 95% CI:   5%|▋             | 23/500 [00:00<00:02, 228.71it/s]
bootstrap micro f1 95% CI:  10%|█▎            | 49/500 [00:00<00:01, 243.86it/s]
bootstrap micro f1 95% CI:  15%|██            | 75/500 [00:00<00:01, 248.50it/s]
bootstrap micro f1 95% CI:  20%|██▋          | 101/500 [00:00<00:01, 250.84it/s]
bootstrap micro f1 95% CI:  25%|███▎         | 127/500 [00:00<00:01, 252.02it/s]
bootstrap micro f1 95% CI:  31%|███▉         | 153/500 [00:00<00:01, 253.03it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 179/500 [00:00<00:01, 253.57it/s]
bootstrap micro f1 95% CI:  41%|█████▎       | 205/500 [00:00<00:01, 253.82it/s]
bootstrap micro f1 95% CI:  46%|██████       | 231/500 [00:00<00:01, 254.12it/s]
bootstrap micro f1 95% CI:  51%|██████▋      | 257/500 [00:01<00:00, 254.55it/s]
bootstrap micro f1 95% CI:  57%|███████▎     | 283/500 [00:01<00:00, 254.70it/s]
bootstrap micro f1 95% CI:  62%|████████     | 309/500 [00:01<00:00, 254.59it/s]
bootstrap micro f1 95% CI:  67%|████████▋    | 335/500 [00:01<00:00, 254.64it/s]
bootstrap micro f1 95% CI:  72%|█████████▍   | 361/500 [00:01<00:00, 254.68it/s]
bootstrap micro f1 95% CI:  77%|██████████   | 387/500 [00:01<00:00, 254.69it/s]
bootstrap micro f1 95% CI:  83%|██████████▋  | 413/500 [00:01<00:00, 254.85it/s]
bootstrap micro f1 95% CI:  88%|███████████▍ | 439/500 [00:01<00:00, 254.86it/s]
bootstrap micro f1 95% CI:  93%|████████████ | 465/500 [00:01<00:00, 255.00it/s]
bootstrap micro f1 95% CI:  98%|████████████▊| 491/500 [00:01<00:00, 254.98it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 253.33it/s]


bootstrap macro f1 95% CI:   5%|▋             | 24/500 [00:00<00:02, 232.67it/s]

bootstrap macro f1 95% CI:  10%|█▍            | 50/500 [00:00<00:01, 246.04it/s]

bootstrap macro f1 95% CI:  15%|██▏           | 76/500 [00:00<00:01, 250.75it/s]

bootstrap macro f1 95% CI:  20%|██▋          | 102/500 [00:00<00:01, 252.67it/s]

bootstrap macro f1 95% CI:  26%|███▎         | 128/500 [00:00<00:01, 253.66it/s]

bootstrap macro f1 95% CI:  31%|████         | 154/500 [00:00<00:01, 254.16it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 180/500 [00:00<00:01, 254.55it/s]

bootstrap macro f1 95% CI:  41%|█████▎       | 206/500 [00:00<00:01, 254.90it/s]

bootstrap macro f1 95% CI:  46%|██████       | 232/500 [00:00<00:01, 255.01it/s]

bootstrap macro f1 95% CI:  52%|██████▋      | 258/500 [00:01<00:00, 255.24it/s]

bootstrap macro f1 95% CI:  57%|███████▍     | 284/500 [00:01<00:00, 255.27it/s]

bootstrap macro f1 95% CI:  62%|████████     | 310/500 [00:01<00:00, 255.36it/s]

bootstrap macro f1 95% CI:  67%|████████▋    | 336/500 [00:01<00:00, 255.45it/s]

bootstrap macro f1 95% CI:  72%|█████████▍   | 362/500 [00:01<00:00, 255.36it/s]

bootstrap macro f1 95% CI:  78%|██████████   | 388/500 [00:01<00:00, 255.20it/s]

bootstrap macro f1 95% CI:  83%|██████████▊  | 414/500 [00:01<00:00, 255.00it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 440/500 [00:01<00:00, 254.97it/s]

bootstrap macro f1 95% CI:  93%|████████████ | 466/500 [00:01<00:00, 254.85it/s]

bootstrap macro f1 95% CI:  98%|████████████▊| 492/500 [00:01<00:00, 254.90it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 252.24it/s]

bootstrap micro f1 95% CI:   2%|▎             | 12/500 [00:00<00:04, 119.15it/s]
bootstrap micro f1 95% CI:   5%|▋             | 26/500 [00:00<00:03, 128.18it/s]
bootstrap micro f1 95% CI:   8%|█             | 40/500 [00:00<00:03, 130.82it/s]
bootstrap micro f1 95% CI:  11%|█▌            | 54/500 [00:00<00:03, 132.48it/s]
bootstrap micro f1 95% CI:  14%|█▉            | 68/500 [00:00<00:03, 133.21it/s]
bootstrap micro f1 95% CI:  16%|██▎           | 82/500 [00:00<00:03, 133.79it/s]
bootstrap micro f1 95% CI:  19%|██▋           | 96/500 [00:00<00:03, 134.17it/s]
bootstrap micro f1 95% CI:  22%|██▊          | 110/500 [00:00<00:02, 134.39it/s]
bootstrap micro f1 95% CI:  25%|███▏         | 124/500 [00:00<00:02, 134.55it/s]
bootstrap micro f1 95% CI:  28%|███▌         | 138/500 [00:01<00:02, 134.46it/s]
bootstrap micro f1 95% CI:  30%|███▉         | 152/500 [00:01<00:02, 134.29it/s]
bootstrap micro f1 95% CI:  33%|████▎        | 166/500 [00:01<00:02, 134.49it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 180/500 [00:01<00:02, 134.63it/s]
bootstrap micro f1 95% CI:  39%|█████        | 194/500 [00:01<00:02, 134.58it/s]
bootstrap micro f1 95% CI:  42%|█████▍       | 208/500 [00:01<00:02, 134.46it/s]
bootstrap micro f1 95% CI:  44%|█████▊       | 222/500 [00:01<00:02, 134.77it/s]
bootstrap micro f1 95% CI:  47%|██████▏      | 236/500 [00:01<00:01, 134.60it/s]
bootstrap micro f1 95% CI:  50%|██████▌      | 250/500 [00:01<00:01, 134.66it/s]
bootstrap micro f1 95% CI:  53%|██████▊      | 264/500 [00:01<00:01, 134.77it/s]
bootstrap micro f1 95% CI:  56%|███████▏     | 278/500 [00:02<00:01, 134.76it/s]
bootstrap micro f1 95% CI:  58%|███████▌     | 292/500 [00:02<00:01, 134.91it/s]
bootstrap micro f1 95% CI:  61%|███████▉     | 306/500 [00:02<00:01, 134.75it/s]
bootstrap micro f1 95% CI:  64%|████████▎    | 320/500 [00:02<00:01, 134.90it/s]
bootstrap micro f1 95% CI:  67%|████████▋    | 334/500 [00:02<00:01, 135.23it/s]
bootstrap micro f1 95% CI:  70%|█████████    | 348/500 [00:02<00:01, 134.30it/s]
bootstrap micro f1 95% CI:  72%|█████████▍   | 362/500 [00:02<00:01, 134.52it/s]
bootstrap micro f1 95% CI:  75%|█████████▊   | 376/500 [00:02<00:00, 134.47it/s]
bootstrap micro f1 95% CI:  78%|██████████▏  | 390/500 [00:02<00:00, 134.62it/s]
bootstrap micro f1 95% CI:  81%|██████████▌  | 404/500 [00:03<00:00, 134.72it/s]
bootstrap micro f1 95% CI:  84%|██████████▊  | 418/500 [00:03<00:00, 134.83it/s]
bootstrap micro f1 95% CI:  86%|███████████▏ | 432/500 [00:03<00:00, 134.76it/s]
bootstrap micro f1 95% CI:  89%|███████████▌ | 446/500 [00:03<00:00, 134.62it/s]
bootstrap micro f1 95% CI:  92%|███████████▉ | 460/500 [00:03<00:00, 134.63it/s]
bootstrap micro f1 95% CI:  95%|████████████▎| 474/500 [00:03<00:00, 134.76it/s]
bootstrap micro f1 95% CI:  98%|████████████▋| 488/500 [00:03<00:00, 134.80it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 134.22it/s]


bootstrap macro f1 95% CI:   3%|▎             | 13/500 [00:00<00:03, 122.80it/s]

bootstrap macro f1 95% CI:   5%|▊             | 27/500 [00:00<00:03, 130.16it/s]

bootstrap macro f1 95% CI:   8%|█▏            | 41/500 [00:00<00:03, 131.33it/s]

bootstrap macro f1 95% CI:  11%|█▌            | 55/500 [00:00<00:03, 132.87it/s]

bootstrap macro f1 95% CI:  14%|█▉            | 69/500 [00:00<00:03, 133.65it/s]

bootstrap macro f1 95% CI:  17%|██▎           | 83/500 [00:00<00:03, 134.17it/s]

bootstrap macro f1 95% CI:  19%|██▋           | 97/500 [00:00<00:02, 134.35it/s]

bootstrap macro f1 95% CI:  22%|██▉          | 111/500 [00:00<00:02, 134.49it/s]

bootstrap macro f1 95% CI:  25%|███▎         | 125/500 [00:00<00:02, 134.64it/s]

bootstrap macro f1 95% CI:  28%|███▌         | 139/500 [00:01<00:02, 134.80it/s]

bootstrap macro f1 95% CI:  31%|███▉         | 153/500 [00:01<00:02, 134.85it/s]

bootstrap macro f1 95% CI:  33%|████▎        | 167/500 [00:01<00:02, 135.14it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 181/500 [00:01<00:02, 135.33it/s]

bootstrap macro f1 95% CI:  39%|█████        | 195/500 [00:01<00:02, 135.17it/s]

bootstrap macro f1 95% CI:  42%|█████▍       | 209/500 [00:01<00:02, 135.19it/s]

bootstrap macro f1 95% CI:  45%|█████▊       | 223/500 [00:01<00:02, 135.29it/s]

bootstrap macro f1 95% CI:  47%|██████▏      | 237/500 [00:01<00:01, 134.01it/s]

bootstrap macro f1 95% CI:  50%|██████▌      | 251/500 [00:01<00:01, 134.33it/s]

bootstrap macro f1 95% CI:  53%|██████▉      | 265/500 [00:01<00:01, 134.61it/s]

bootstrap macro f1 95% CI:  56%|███████▎     | 279/500 [00:02<00:01, 134.82it/s]

bootstrap macro f1 95% CI:  59%|███████▌     | 293/500 [00:02<00:01, 134.82it/s]

bootstrap macro f1 95% CI:  61%|███████▉     | 307/500 [00:02<00:01, 134.68it/s]

bootstrap macro f1 95% CI:  64%|████████▎    | 321/500 [00:02<00:01, 134.71it/s]

bootstrap macro f1 95% CI:  67%|████████▋    | 335/500 [00:02<00:01, 134.82it/s]

bootstrap macro f1 95% CI:  70%|█████████    | 349/500 [00:02<00:01, 134.84it/s]

bootstrap macro f1 95% CI:  73%|█████████▍   | 363/500 [00:02<00:01, 134.88it/s]

bootstrap macro f1 95% CI:  75%|█████████▊   | 377/500 [00:02<00:00, 134.90it/s]

bootstrap macro f1 95% CI:  78%|██████████▏  | 391/500 [00:02<00:00, 134.83it/s]

bootstrap macro f1 95% CI:  81%|██████████▌  | 405/500 [00:03<00:00, 135.07it/s]

bootstrap macro f1 95% CI:  84%|██████████▉  | 419/500 [00:03<00:00, 135.09it/s]

bootstrap macro f1 95% CI:  87%|███████████▎ | 433/500 [00:03<00:00, 133.41it/s]

bootstrap macro f1 95% CI:  89%|███████████▌ | 447/500 [00:03<00:00, 133.76it/s]

bootstrap macro f1 95% CI:  92%|███████████▉ | 461/500 [00:03<00:00, 134.21it/s]

bootstrap macro f1 95% CI:  95%|████████████▎| 475/500 [00:03<00:00, 134.57it/s]

bootstrap macro f1 95% CI:  98%|████████████▋| 489/500 [00:03<00:00, 134.78it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 134.16it/s]

bootstrap micro f1 95% CI:   5%|▋             | 23/500 [00:00<00:02, 227.28it/s]
bootstrap micro f1 95% CI:  10%|█▎            | 49/500 [00:00<00:01, 241.08it/s]
bootstrap micro f1 95% CI:  15%|██            | 75/500 [00:00<00:01, 245.16it/s]
bootstrap micro f1 95% CI:  20%|██▌          | 100/500 [00:00<00:01, 246.69it/s]
bootstrap micro f1 95% CI:  25%|███▎         | 125/500 [00:00<00:01, 247.64it/s]
bootstrap micro f1 95% CI:  30%|███▉         | 150/500 [00:00<00:01, 248.44it/s]
bootstrap micro f1 95% CI:  35%|████▌        | 175/500 [00:00<00:01, 248.81it/s]
bootstrap micro f1 95% CI:  40%|█████▏       | 200/500 [00:00<00:01, 249.11it/s]
bootstrap micro f1 95% CI:  45%|█████▉       | 226/500 [00:00<00:01, 249.41it/s]
bootstrap micro f1 95% CI:  50%|██████▌      | 251/500 [00:01<00:00, 249.57it/s]
bootstrap micro f1 95% CI:  55%|███████▏     | 276/500 [00:01<00:00, 249.65it/s]
bootstrap micro f1 95% CI:  60%|███████▊     | 301/500 [00:01<00:00, 249.64it/s]
bootstrap micro f1 95% CI:  65%|████████▍    | 326/500 [00:01<00:00, 249.72it/s]
bootstrap micro f1 95% CI:  70%|█████████▏   | 352/500 [00:01<00:00, 249.81it/s]
bootstrap micro f1 95% CI:  75%|█████████▊   | 377/500 [00:01<00:00, 249.54it/s]
bootstrap micro f1 95% CI:  80%|██████████▍  | 402/500 [00:01<00:00, 249.46it/s]
bootstrap micro f1 95% CI:  85%|███████████  | 427/500 [00:01<00:00, 249.50it/s]
bootstrap micro f1 95% CI:  90%|███████████▊ | 452/500 [00:01<00:00, 249.55it/s]
bootstrap micro f1 95% CI:  95%|████████████▍| 477/500 [00:01<00:00, 249.63it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:02<00:00, 248.53it/s]


bootstrap macro f1 95% CI:   5%|▋             | 23/500 [00:00<00:02, 227.67it/s]

bootstrap macro f1 95% CI:  10%|█▎            | 49/500 [00:00<00:01, 241.26it/s]

bootstrap macro f1 95% CI:  15%|██            | 75/500 [00:00<00:01, 245.61it/s]

bootstrap macro f1 95% CI:  20%|██▋          | 101/500 [00:00<00:01, 247.36it/s]

bootstrap macro f1 95% CI:  25%|███▎         | 127/500 [00:00<00:01, 248.42it/s]

bootstrap macro f1 95% CI:  31%|███▉         | 153/500 [00:00<00:01, 249.09it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 179/500 [00:00<00:01, 249.67it/s]

bootstrap macro f1 95% CI:  41%|█████▎       | 205/500 [00:00<00:01, 250.00it/s]

bootstrap macro f1 95% CI:  46%|██████       | 231/500 [00:00<00:01, 250.26it/s]

bootstrap macro f1 95% CI:  51%|██████▋      | 257/500 [00:01<00:00, 250.32it/s]

bootstrap macro f1 95% CI:  57%|███████▎     | 283/500 [00:01<00:00, 250.50it/s]

bootstrap macro f1 95% CI:  62%|████████     | 309/500 [00:01<00:00, 250.74it/s]

bootstrap macro f1 95% CI:  67%|████████▋    | 335/500 [00:01<00:00, 250.69it/s]

bootstrap macro f1 95% CI:  72%|█████████▍   | 361/500 [00:01<00:00, 250.80it/s]

bootstrap macro f1 95% CI:  77%|██████████   | 387/500 [00:01<00:00, 250.80it/s]

bootstrap macro f1 95% CI:  83%|██████████▋  | 413/500 [00:01<00:00, 251.04it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 439/500 [00:01<00:00, 251.26it/s]

bootstrap macro f1 95% CI:  93%|████████████ | 465/500 [00:01<00:00, 251.20it/s]

F1-RadGraph:  20%|██████▍                         | 1/5 [00:34<02:17, 34.46s/it]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
ROUGE-L: 100%|████████████████████████████████████| 5/5 [01:21<00:00, 16.22s/it]


Total reports: 1080

========== Main Results ==========
        Micro-F1-14  Micro-F1-5  Macro-F1-14  ...     BLEU-1     BLEU-4   ROUGE-L
median     0.590278    0.595045     0.402081  ...  39.421710  16.641794  0.319198
ci_l       0.574472    0.570496     0.377737  ...  38.377747  15.764659  0.311061
ci_h       0.608799    0.616755     0.427984  ...  40.408268  17.460686  0.327712

[3 rows x 12 columns]

wandb: Currently logged in as: mbhosale (bhosalems_) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.20.1
wandb: Run data is saved locally in /home/csgrad/mbhosale/phd/MrFair/LLaVA-Rad/scripts/wandb/run-20250703_211210-age_44_65
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run age_44_65

In [87]:
!python ../llava/eval/rrg_eval/run.py ../results/llavarad/age_65_inf.jsonl --run_name age_65_inf

[2025-07-03 21:12:20,971] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CheXbert:   0%|                                           | 0/5 [00:00<?, ?it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

bootstrap micro f1 95% CI:   0%|                        | 0/500 [00:00<?, ?it/s]
bootstrap micro f1 95% CI:   2%|▎             | 12/500 [00:00<00:04, 114.12it/s]
bootstrap micro f1 95% CI:   5%|▋             | 26/500 [00:00<00:03, 123.71it/s]
bootstrap micro f1 95% CI:   8%|█             | 39/500 [00:00<00:03, 125.89it/s]
bootstrap micro f1 95% CI:  10%|█▍            | 52/500 [00:00<00:03, 126.63it/s]
bootstrap micro f1 95% CI:  13%|█▊            | 65/500 [00:00<00:03, 127.36it/s]
bootstrap micro f1 95% CI:  16%|██▏           | 78/500 [00:00<00:03, 127.95it/s]
bootstrap micro f1 95% CI:  18%|██▌           | 91/500 [00:00<00:03, 128.04it/s]
bootstrap micro f1 95% CI:  21%|██▋          | 105/500 [00:00<00:03, 128.79it/s]
bootstrap micro f1 95% CI:  24%|███          | 119/500 [00:00<00:02, 129.70it/s]
bootstrap micro f1 95% CI:  27%|███▍         | 133/500 [00:01<00:02, 129.96it/s]
bootstrap micro f1 95% CI:  29%|███▊         | 146/500 [00:01<00:02, 129.44it/s]
bootstrap micro f1 95% CI:  32%|████▏        | 160/500 [00:01<00:02, 129.81it/s]
bootstrap micro f1 95% CI:  35%|████▌        | 174/500 [00:01<00:02, 129.95it/s]
bootstrap micro f1 95% CI:  37%|████▊        | 187/500 [00:01<00:02, 129.41it/s]
bootstrap micro f1 95% CI:  40%|█████▏       | 200/500 [00:01<00:02, 128.42it/s]
bootstrap micro f1 95% CI:  43%|█████▌       | 213/500 [00:01<00:02, 128.85it/s]
bootstrap micro f1 95% CI:  45%|█████▉       | 227/500 [00:01<00:02, 129.49it/s]
bootstrap micro f1 95% CI:  48%|██████▎      | 241/500 [00:01<00:01, 129.65it/s]
bootstrap micro f1 95% CI:  51%|██████▌      | 254/500 [00:01<00:01, 129.64it/s]
bootstrap micro f1 95% CI:  54%|██████▉      | 268/500 [00:02<00:01, 129.86it/s]
bootstrap micro f1 95% CI:  56%|███████▎     | 282/500 [00:02<00:01, 130.19it/s]
bootstrap micro f1 95% CI:  59%|███████▋     | 296/500 [00:02<00:01, 130.12it/s]
bootstrap micro f1 95% CI:  62%|████████     | 310/500 [00:02<00:01, 129.70it/s]
bootstrap micro f1 95% CI:  65%|████████▍    | 323/500 [00:02<00:01, 129.41it/s]
bootstrap micro f1 95% CI:  67%|████████▊    | 337/500 [00:02<00:01, 129.70it/s]
bootstrap micro f1 95% CI:  70%|█████████▏   | 351/500 [00:02<00:01, 130.11it/s]
bootstrap micro f1 95% CI:  73%|█████████▍   | 365/500 [00:02<00:01, 130.31it/s]
bootstrap micro f1 95% CI:  76%|█████████▊   | 379/500 [00:02<00:00, 130.07it/s]
bootstrap micro f1 95% CI:  79%|██████████▏  | 393/500 [00:03<00:00, 130.31it/s]
bootstrap micro f1 95% CI:  81%|██████████▌  | 407/500 [00:03<00:00, 130.67it/s]
bootstrap micro f1 95% CI:  84%|██████████▉  | 421/500 [00:03<00:00, 130.65it/s]
bootstrap micro f1 95% CI:  87%|███████████▎ | 435/500 [00:03<00:00, 130.90it/s]
bootstrap micro f1 95% CI:  90%|███████████▋ | 449/500 [00:03<00:00, 130.35it/s]
bootstrap micro f1 95% CI:  93%|████████████ | 463/500 [00:03<00:00, 129.68it/s]
bootstrap micro f1 95% CI:  95%|████████████▍| 477/500 [00:03<00:00, 129.92it/s]
bootstrap micro f1 95% CI:  98%|████████████▊| 491/500 [00:03<00:00, 130.29it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 129.34it/s]


bootstrap macro f1 95% CI:   2%|▎             | 12/500 [00:00<00:04, 116.59it/s]

bootstrap macro f1 95% CI:   5%|▋             | 25/500 [00:00<00:03, 123.96it/s]

bootstrap macro f1 95% CI:   8%|█             | 38/500 [00:00<00:03, 126.45it/s]

bootstrap macro f1 95% CI:  10%|█▍            | 52/500 [00:00<00:03, 128.28it/s]

bootstrap macro f1 95% CI:  13%|█▊            | 66/500 [00:00<00:03, 129.15it/s]

bootstrap macro f1 95% CI:  16%|██▏           | 79/500 [00:00<00:03, 129.31it/s]

bootstrap macro f1 95% CI:  19%|██▌           | 93/500 [00:00<00:03, 129.77it/s]

bootstrap macro f1 95% CI:  21%|██▊          | 106/500 [00:00<00:03, 129.22it/s]

bootstrap macro f1 95% CI:  24%|███          | 120/500 [00:00<00:02, 129.65it/s]

bootstrap macro f1 95% CI:  27%|███▍         | 134/500 [00:01<00:02, 129.88it/s]

bootstrap macro f1 95% CI:  30%|███▊         | 148/500 [00:01<00:02, 129.96it/s]

bootstrap macro f1 95% CI:  32%|████▏        | 162/500 [00:01<00:02, 130.30it/s]

bootstrap macro f1 95% CI:  35%|████▌        | 176/500 [00:01<00:02, 130.51it/s]

bootstrap macro f1 95% CI:  38%|████▉        | 190/500 [00:01<00:02, 130.41it/s]

bootstrap macro f1 95% CI:  41%|█████▎       | 204/500 [00:01<00:02, 130.62it/s]

bootstrap macro f1 95% CI:  44%|█████▋       | 218/500 [00:01<00:02, 130.26it/s]

bootstrap macro f1 95% CI:  46%|██████       | 232/500 [00:01<00:02, 130.25it/s]

bootstrap macro f1 95% CI:  49%|██████▍      | 246/500 [00:01<00:01, 129.13it/s]

bootstrap macro f1 95% CI:  52%|██████▊      | 260/500 [00:02<00:01, 129.54it/s]

bootstrap macro f1 95% CI:  55%|███████      | 274/500 [00:02<00:01, 129.81it/s]

bootstrap macro f1 95% CI:  58%|███████▍     | 288/500 [00:02<00:01, 130.04it/s]

bootstrap macro f1 95% CI:  60%|███████▊     | 302/500 [00:02<00:01, 130.14it/s]

bootstrap macro f1 95% CI:  63%|████████▏    | 316/500 [00:02<00:01, 130.24it/s]

bootstrap macro f1 95% CI:  66%|████████▌    | 330/500 [00:02<00:01, 130.41it/s]

bootstrap macro f1 95% CI:  69%|████████▉    | 344/500 [00:02<00:01, 130.35it/s]

bootstrap macro f1 95% CI:  72%|█████████▎   | 358/500 [00:02<00:01, 130.01it/s]

bootstrap macro f1 95% CI:  74%|█████████▋   | 372/500 [00:02<00:00, 130.29it/s]

bootstrap macro f1 95% CI:  77%|██████████   | 386/500 [00:02<00:00, 129.16it/s]

bootstrap macro f1 95% CI:  80%|██████████▎  | 399/500 [00:03<00:00, 129.33it/s]

bootstrap macro f1 95% CI:  82%|██████████▋  | 412/500 [00:03<00:00, 129.45it/s]

bootstrap macro f1 95% CI:  85%|███████████  | 425/500 [00:03<00:00, 129.56it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 439/500 [00:03<00:00, 129.91it/s]

bootstrap macro f1 95% CI:  91%|███████████▊ | 453/500 [00:03<00:00, 129.97it/s]

bootstrap macro f1 95% CI:  93%|████████████▏| 467/500 [00:03<00:00, 130.03it/s]

bootstrap macro f1 95% CI:  96%|████████████▌| 481/500 [00:03<00:00, 129.74it/s]

bootstrap macro f1 95% CI:  99%|████████████▊| 494/500 [00:03<00:00, 129.65it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 129.33it/s]

bootstrap micro f1 95% CI:   4%|▌             | 22/500 [00:00<00:02, 216.92it/s]
bootstrap micro f1 95% CI:   9%|█▎            | 46/500 [00:00<00:02, 225.59it/s]
bootstrap micro f1 95% CI:  14%|█▉            | 71/500 [00:00<00:01, 233.31it/s]
bootstrap micro f1 95% CI:  19%|██▋           | 96/500 [00:00<00:01, 236.75it/s]
bootstrap micro f1 95% CI:  24%|███▏         | 121/500 [00:00<00:01, 238.48it/s]
bootstrap micro f1 95% CI:  29%|███▊         | 146/500 [00:00<00:01, 239.26it/s]
bootstrap micro f1 95% CI:  34%|████▍        | 171/500 [00:00<00:01, 239.90it/s]
bootstrap micro f1 95% CI:  39%|█████        | 196/500 [00:00<00:01, 239.92it/s]
bootstrap micro f1 95% CI:  44%|█████▋       | 220/500 [00:00<00:01, 238.77it/s]
bootstrap micro f1 95% CI:  49%|██████▎      | 245/500 [00:01<00:01, 239.68it/s]
bootstrap micro f1 95% CI:  54%|███████      | 270/500 [00:01<00:00, 240.28it/s]
bootstrap micro f1 95% CI:  59%|███████▋     | 295/500 [00:01<00:00, 240.58it/s]
bootstrap micro f1 95% CI:  64%|████████▎    | 320/500 [00:01<00:00, 239.36it/s]
bootstrap micro f1 95% CI:  69%|████████▉    | 345/500 [00:01<00:00, 239.71it/s]
bootstrap micro f1 95% CI:  74%|█████████▌   | 370/500 [00:01<00:00, 240.13it/s]
bootstrap micro f1 95% CI:  79%|██████████▎  | 395/500 [00:01<00:00, 240.62it/s]
bootstrap micro f1 95% CI:  84%|██████████▉  | 420/500 [00:01<00:00, 240.55it/s]
bootstrap micro f1 95% CI:  89%|███████████▌ | 445/500 [00:01<00:00, 240.50it/s]
bootstrap micro f1 95% CI:  94%|████████████▏| 470/500 [00:01<00:00, 239.68it/s]
bootstrap micro f1 95% CI:  99%|████████████▊| 495/500 [00:02<00:00, 240.23it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:02<00:00, 238.82it/s]


bootstrap macro f1 95% CI:   4%|▌             | 22/500 [00:00<00:02, 215.97it/s]

bootstrap macro f1 95% CI:   9%|█▎            | 47/500 [00:00<00:01, 230.80it/s]

bootstrap macro f1 95% CI:  14%|█▉            | 71/500 [00:00<00:01, 234.10it/s]

bootstrap macro f1 95% CI:  19%|██▋           | 95/500 [00:00<00:01, 235.71it/s]

bootstrap macro f1 95% CI:  24%|███          | 120/500 [00:00<00:01, 237.88it/s]

bootstrap macro f1 95% CI:  29%|███▊         | 145/500 [00:00<00:01, 239.26it/s]

bootstrap macro f1 95% CI:  34%|████▍        | 170/500 [00:00<00:01, 240.02it/s]

bootstrap macro f1 95% CI:  39%|█████        | 194/500 [00:00<00:01, 239.58it/s]

bootstrap macro f1 95% CI:  44%|█████▋       | 218/500 [00:00<00:01, 239.66it/s]

bootstrap macro f1 95% CI:  48%|██████▎      | 242/500 [00:01<00:01, 239.48it/s]

bootstrap macro f1 95% CI:  53%|██████▉      | 267/500 [00:01<00:00, 240.10it/s]

bootstrap macro f1 95% CI:  58%|███████▌     | 292/500 [00:01<00:00, 240.44it/s]

bootstrap macro f1 95% CI:  63%|████████▏    | 317/500 [00:01<00:00, 240.89it/s]

bootstrap macro f1 95% CI:  68%|████████▉    | 342/500 [00:01<00:00, 240.98it/s]

bootstrap macro f1 95% CI:  73%|█████████▌   | 367/500 [00:01<00:00, 240.91it/s]

bootstrap macro f1 95% CI:  78%|██████████▏  | 392/500 [00:01<00:00, 241.01it/s]

bootstrap macro f1 95% CI:  83%|██████████▊  | 417/500 [00:01<00:00, 241.16it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 442/500 [00:01<00:00, 240.28it/s]

bootstrap macro f1 95% CI:  93%|████████████▏| 467/500 [00:01<00:00, 239.49it/s]

bootstrap macro f1 95% CI:  98%|████████████▊| 492/500 [00:02<00:00, 240.12it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:02<00:00, 237.42it/s]

bootstrap micro f1 95% CI:   2%|▎             | 12/500 [00:00<00:04, 114.62it/s]
bootstrap micro f1 95% CI:   5%|▋             | 25/500 [00:00<00:03, 122.54it/s]
bootstrap micro f1 95% CI:   8%|█             | 38/500 [00:00<00:03, 125.07it/s]
bootstrap micro f1 95% CI:  10%|█▍            | 51/500 [00:00<00:03, 126.14it/s]
bootstrap micro f1 95% CI:  13%|█▊            | 64/500 [00:00<00:03, 125.92it/s]
bootstrap micro f1 95% CI:  15%|██▏           | 77/500 [00:00<00:03, 126.58it/s]
bootstrap micro f1 95% CI:  18%|██▌           | 90/500 [00:00<00:03, 126.91it/s]
bootstrap micro f1 95% CI:  21%|██▋          | 103/500 [00:00<00:03, 126.13it/s]
bootstrap micro f1 95% CI:  23%|███          | 116/500 [00:00<00:03, 126.66it/s]
bootstrap micro f1 95% CI:  26%|███▎         | 129/500 [00:01<00:02, 126.81it/s]
bootstrap micro f1 95% CI:  28%|███▋         | 142/500 [00:01<00:02, 127.33it/s]
bootstrap micro f1 95% CI:  31%|████         | 155/500 [00:01<00:02, 127.59it/s]
bootstrap micro f1 95% CI:  34%|████▎        | 168/500 [00:01<00:02, 127.38it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 181/500 [00:01<00:02, 127.41it/s]
bootstrap micro f1 95% CI:  39%|█████        | 194/500 [00:01<00:02, 127.33it/s]
bootstrap micro f1 95% CI:  41%|█████▍       | 207/500 [00:01<00:02, 127.04it/s]
bootstrap micro f1 95% CI:  44%|█████▋       | 220/500 [00:01<00:02, 126.24it/s]
bootstrap micro f1 95% CI:  47%|██████       | 233/500 [00:01<00:02, 126.42it/s]
bootstrap micro f1 95% CI:  49%|██████▍      | 246/500 [00:01<00:02, 126.94it/s]
bootstrap micro f1 95% CI:  52%|██████▋      | 259/500 [00:02<00:01, 127.32it/s]
bootstrap micro f1 95% CI:  54%|███████      | 272/500 [00:02<00:01, 127.39it/s]
bootstrap micro f1 95% CI:  57%|███████▍     | 285/500 [00:02<00:01, 127.65it/s]
bootstrap micro f1 95% CI:  60%|███████▋     | 298/500 [00:02<00:01, 127.83it/s]
bootstrap micro f1 95% CI:  62%|████████     | 311/500 [00:02<00:01, 128.10it/s]
bootstrap micro f1 95% CI:  65%|████████▍    | 324/500 [00:02<00:01, 128.28it/s]
bootstrap micro f1 95% CI:  67%|████████▊    | 337/500 [00:02<00:01, 128.32it/s]
bootstrap micro f1 95% CI:  70%|█████████    | 350/500 [00:02<00:01, 128.27it/s]
bootstrap micro f1 95% CI:  73%|█████████▍   | 363/500 [00:02<00:01, 128.04it/s]
bootstrap micro f1 95% CI:  75%|█████████▊   | 376/500 [00:02<00:00, 128.05it/s]
bootstrap micro f1 95% CI:  78%|██████████   | 389/500 [00:03<00:00, 127.94it/s]
bootstrap micro f1 95% CI:  80%|██████████▍  | 402/500 [00:03<00:00, 127.90it/s]
bootstrap micro f1 95% CI:  83%|██████████▊  | 415/500 [00:03<00:00, 128.00it/s]
bootstrap micro f1 95% CI:  86%|███████████▏ | 428/500 [00:03<00:00, 127.93it/s]
bootstrap micro f1 95% CI:  88%|███████████▍ | 441/500 [00:03<00:00, 127.98it/s]
bootstrap micro f1 95% CI:  91%|███████████▊ | 454/500 [00:03<00:00, 128.01it/s]
bootstrap micro f1 95% CI:  93%|████████████▏| 467/500 [00:03<00:00, 128.05it/s]
bootstrap micro f1 95% CI:  96%|████████████▍| 480/500 [00:03<00:00, 128.17it/s]
bootstrap micro f1 95% CI:  99%|████████████▊| 493/500 [00:03<00:00, 128.15it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 127.27it/s]


bootstrap macro f1 95% CI:   2%|▎             | 12/500 [00:00<00:04, 114.60it/s]

bootstrap macro f1 95% CI:   5%|▋             | 25/500 [00:00<00:03, 122.57it/s]

bootstrap macro f1 95% CI:   8%|█             | 38/500 [00:00<00:03, 124.96it/s]

bootstrap macro f1 95% CI:  10%|█▍            | 51/500 [00:00<00:03, 126.24it/s]

bootstrap macro f1 95% CI:  13%|█▊            | 64/500 [00:00<00:03, 126.77it/s]

bootstrap macro f1 95% CI:  15%|██▏           | 77/500 [00:00<00:03, 126.99it/s]

bootstrap macro f1 95% CI:  18%|██▌           | 90/500 [00:00<00:03, 127.09it/s]

bootstrap macro f1 95% CI:  21%|██▋          | 103/500 [00:00<00:03, 127.21it/s]

bootstrap macro f1 95% CI:  23%|███          | 116/500 [00:00<00:03, 127.36it/s]

bootstrap macro f1 95% CI:  26%|███▎         | 129/500 [00:01<00:02, 127.36it/s]

bootstrap macro f1 95% CI:  28%|███▋         | 142/500 [00:01<00:02, 127.54it/s]

bootstrap macro f1 95% CI:  31%|████         | 155/500 [00:01<00:02, 127.75it/s]

bootstrap macro f1 95% CI:  34%|████▎        | 168/500 [00:01<00:02, 127.91it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 181/500 [00:01<00:02, 127.89it/s]

bootstrap macro f1 95% CI:  39%|█████        | 194/500 [00:01<00:02, 128.03it/s]

bootstrap macro f1 95% CI:  41%|█████▍       | 207/500 [00:01<00:02, 127.94it/s]

bootstrap macro f1 95% CI:  44%|█████▋       | 220/500 [00:01<00:02, 127.88it/s]

bootstrap macro f1 95% CI:  47%|██████       | 233/500 [00:01<00:02, 128.13it/s]

bootstrap macro f1 95% CI:  49%|██████▍      | 246/500 [00:01<00:01, 127.93it/s]

bootstrap macro f1 95% CI:  52%|██████▋      | 259/500 [00:02<00:01, 127.53it/s]

bootstrap macro f1 95% CI:  54%|███████      | 272/500 [00:02<00:01, 127.60it/s]

bootstrap macro f1 95% CI:  57%|███████▍     | 285/500 [00:02<00:01, 127.63it/s]

bootstrap macro f1 95% CI:  60%|███████▋     | 298/500 [00:02<00:01, 127.63it/s]

bootstrap macro f1 95% CI:  62%|████████     | 311/500 [00:02<00:01, 127.58it/s]

bootstrap macro f1 95% CI:  65%|████████▍    | 324/500 [00:02<00:01, 127.68it/s]

bootstrap macro f1 95% CI:  67%|████████▊    | 337/500 [00:02<00:01, 127.76it/s]

bootstrap macro f1 95% CI:  70%|█████████    | 350/500 [00:02<00:01, 127.89it/s]

bootstrap macro f1 95% CI:  73%|█████████▍   | 363/500 [00:02<00:01, 127.97it/s]

bootstrap macro f1 95% CI:  75%|█████████▊   | 376/500 [00:02<00:00, 127.84it/s]

bootstrap macro f1 95% CI:  78%|██████████   | 389/500 [00:03<00:00, 127.21it/s]

bootstrap macro f1 95% CI:  80%|██████████▍  | 402/500 [00:03<00:00, 127.49it/s]

bootstrap macro f1 95% CI:  83%|██████████▊  | 415/500 [00:03<00:00, 127.65it/s]

bootstrap macro f1 95% CI:  86%|███████████▏ | 428/500 [00:03<00:00, 127.24it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 441/500 [00:03<00:00, 127.27it/s]

bootstrap macro f1 95% CI:  91%|███████████▊ | 454/500 [00:03<00:00, 127.47it/s]

bootstrap macro f1 95% CI:  93%|████████████▏| 467/500 [00:03<00:00, 127.42it/s]

bootstrap macro f1 95% CI:  96%|████████████▍| 480/500 [00:03<00:00, 127.09it/s]

bootstrap macro f1 95% CI:  99%|████████████▊| 493/500 [00:03<00:00, 127.35it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:03<00:00, 127.10it/s]

bootstrap micro f1 95% CI:   4%|▌             | 22/500 [00:00<00:02, 213.57it/s]
bootstrap micro f1 95% CI:   9%|█▎            | 46/500 [00:00<00:02, 226.46it/s]
bootstrap micro f1 95% CI:  14%|█▉            | 70/500 [00:00<00:01, 231.29it/s]
bootstrap micro f1 95% CI:  19%|██▋           | 94/500 [00:00<00:01, 233.43it/s]
bootstrap micro f1 95% CI:  24%|███          | 118/500 [00:00<00:01, 234.53it/s]
bootstrap micro f1 95% CI:  28%|███▋         | 142/500 [00:00<00:01, 235.38it/s]
bootstrap micro f1 95% CI:  33%|████▎        | 166/500 [00:00<00:01, 235.67it/s]
bootstrap micro f1 95% CI:  38%|████▉        | 190/500 [00:00<00:01, 236.10it/s]
bootstrap micro f1 95% CI:  43%|█████▌       | 214/500 [00:00<00:01, 235.73it/s]
bootstrap micro f1 95% CI:  48%|██████▏      | 238/500 [00:01<00:01, 236.37it/s]
bootstrap micro f1 95% CI:  52%|██████▊      | 262/500 [00:01<00:01, 236.09it/s]
bootstrap micro f1 95% CI:  57%|███████▍     | 286/500 [00:01<00:00, 235.97it/s]
bootstrap micro f1 95% CI:  62%|████████     | 310/500 [00:01<00:00, 236.32it/s]
bootstrap micro f1 95% CI:  67%|████████▋    | 334/500 [00:01<00:00, 236.08it/s]
bootstrap micro f1 95% CI:  72%|█████████▎   | 358/500 [00:01<00:00, 235.76it/s]
bootstrap micro f1 95% CI:  76%|█████████▉   | 382/500 [00:01<00:00, 236.15it/s]
bootstrap micro f1 95% CI:  81%|██████████▌  | 406/500 [00:01<00:00, 236.24it/s]
bootstrap micro f1 95% CI:  86%|███████████▏ | 430/500 [00:01<00:00, 236.07it/s]
bootstrap micro f1 95% CI:  91%|███████████▊ | 454/500 [00:01<00:00, 236.23it/s]
bootstrap micro f1 95% CI:  96%|████████████▍| 478/500 [00:02<00:00, 236.58it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:02<00:00, 235.17it/s]


bootstrap macro f1 95% CI:   4%|▌             | 22/500 [00:00<00:02, 212.73it/s]

bootstrap macro f1 95% CI:   9%|█▎            | 46/500 [00:00<00:02, 223.70it/s]

bootstrap macro f1 95% CI:  14%|█▉            | 70/500 [00:00<00:01, 229.75it/s]

bootstrap macro f1 95% CI:  19%|██▋           | 94/500 [00:00<00:01, 232.02it/s]

bootstrap macro f1 95% CI:  24%|███          | 118/500 [00:00<00:01, 233.87it/s]

bootstrap macro f1 95% CI:  28%|███▋         | 142/500 [00:00<00:01, 234.42it/s]

bootstrap macro f1 95% CI:  33%|████▎        | 166/500 [00:00<00:01, 234.58it/s]

bootstrap macro f1 95% CI:  38%|████▉        | 190/500 [00:00<00:01, 234.90it/s]

bootstrap macro f1 95% CI:  43%|█████▌       | 214/500 [00:00<00:01, 235.58it/s]

bootstrap macro f1 95% CI:  48%|██████▏      | 238/500 [00:01<00:01, 235.92it/s]

bootstrap macro f1 95% CI:  52%|██████▊      | 262/500 [00:01<00:01, 235.89it/s]

bootstrap macro f1 95% CI:  57%|███████▍     | 286/500 [00:01<00:00, 236.23it/s]

bootstrap macro f1 95% CI:  62%|████████     | 310/500 [00:01<00:00, 236.47it/s]

bootstrap macro f1 95% CI:  67%|████████▋    | 334/500 [00:01<00:00, 236.58it/s]

bootstrap macro f1 95% CI:  72%|█████████▎   | 358/500 [00:01<00:00, 236.65it/s]

bootstrap macro f1 95% CI:  76%|█████████▉   | 382/500 [00:01<00:00, 236.37it/s]

bootstrap macro f1 95% CI:  81%|██████████▌  | 406/500 [00:01<00:00, 236.17it/s]

bootstrap macro f1 95% CI:  86%|███████████▏ | 430/500 [00:01<00:00, 236.51it/s]

bootstrap macro f1 95% CI:  91%|███████████▊ | 454/500 [00:01<00:00, 234.37it/s]


#### 3. Race

In [47]:
!python ../llava/eval/rrg_eval/run.py ../results/llavarad/race_white.jsonl --run_name race_white

[2025-07-04 18:23:21,280] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CheXbert:   0%|                                           | 0/5 [00:00<?, ?it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

bootstrap micro f1 95% CI:   0%|                        | 0/500 [00:00<?, ?it/s]
bootstrap micro f1 95% CI:   2%|▎               | 9/500 [00:00<00:05, 84.37it/s]
bootstrap micro f1 95% CI:   4%|▌              | 19/500 [00:00<00:05, 88.08it/s]
bootstrap micro f1 95% CI:   6%|▊              | 29/500 [00:00<00:05, 91.14it/s]
bootstrap micro f1 95% CI:   8%|█▏             | 39/500 [00:00<00:04, 92.39it/s]
bootstrap micro f1 95% CI:  10%|█▍             | 49/500 [00:00<00:04, 90.98it/s]
bootstrap micro f1 95% CI:  12%|█▊             | 59/500 [00:00<00:04, 92.01it/s]
bootstrap micro f1 95% CI:  14%|██             | 69/500 [00:00<00:04, 93.11it/s]
bootstrap micro f1 95% CI:  16%|██▎            | 79/500 [00:00<00:04, 92.53it/s]
bootstrap micro f1 95% CI:  18%|██▋            | 89/500 [00:00<00:04, 93.23it/s]
bootstrap micro f1 95% CI:  20%|██▉            | 99/500 [00:01<00:04, 93.37it/s]
bootstrap micro f1 95% CI:  22%|███           | 109/500 [00:01<00:04, 93.82it/s]
bootstrap micro f1 95% CI:  24%|███▎          | 119/500 [00:01<00:04, 93.81it/s]
bootstrap micro f1 95% CI:  26%|███▌          | 129/500 [00:01<00:03, 93.95it/s]
bootstrap micro f1 95% CI:  28%|███▉          | 139/500 [00:01<00:03, 91.99it/s]
bootstrap micro f1 95% CI:  30%|████▏         | 149/500 [00:01<00:03, 92.62it/s]
bootstrap micro f1 95% CI:  32%|████▍         | 159/500 [00:01<00:03, 93.17it/s]
bootstrap micro f1 95% CI:  34%|████▋         | 169/500 [00:01<00:03, 92.90it/s]
bootstrap micro f1 95% CI:  36%|█████         | 179/500 [00:01<00:03, 93.62it/s]
bootstrap micro f1 95% CI:  38%|█████▎        | 189/500 [00:02<00:03, 93.61it/s]
bootstrap micro f1 95% CI:  40%|█████▌        | 199/500 [00:02<00:03, 93.83it/s]
bootstrap micro f1 95% CI:  42%|█████▊        | 209/500 [00:02<00:03, 93.61it/s]
bootstrap micro f1 95% CI:  44%|██████▏       | 219/500 [00:02<00:02, 94.42it/s]
bootstrap micro f1 95% CI:  46%|██████▍       | 229/500 [00:02<00:02, 94.48it/s]
bootstrap micro f1 95% CI:  48%|██████▋       | 239/500 [00:02<00:02, 94.20it/s]
bootstrap micro f1 95% CI:  50%|██████▉       | 249/500 [00:02<00:02, 94.08it/s]
bootstrap micro f1 95% CI:  52%|███████▎      | 259/500 [00:02<00:02, 94.35it/s]
bootstrap micro f1 95% CI:  54%|███████▌      | 269/500 [00:02<00:02, 94.28it/s]
bootstrap micro f1 95% CI:  56%|███████▊      | 279/500 [00:02<00:02, 94.37it/s]
bootstrap micro f1 95% CI:  58%|████████      | 289/500 [00:03<00:02, 94.13it/s]
bootstrap micro f1 95% CI:  60%|████████▎     | 299/500 [00:03<00:02, 93.71it/s]
bootstrap micro f1 95% CI:  62%|████████▋     | 309/500 [00:03<00:02, 94.07it/s]
bootstrap micro f1 95% CI:  64%|████████▉     | 319/500 [00:03<00:01, 94.33it/s]
bootstrap micro f1 95% CI:  66%|█████████▏    | 329/500 [00:03<00:01, 93.40it/s]
bootstrap micro f1 95% CI:  68%|█████████▍    | 339/500 [00:03<00:01, 93.78it/s]
bootstrap micro f1 95% CI:  70%|█████████▊    | 349/500 [00:03<00:01, 94.10it/s]
bootstrap micro f1 95% CI:  72%|██████████    | 359/500 [00:03<00:01, 94.41it/s]
bootstrap micro f1 95% CI:  74%|██████████▎   | 369/500 [00:03<00:01, 94.74it/s]
bootstrap micro f1 95% CI:  76%|██████████▌   | 379/500 [00:04<00:01, 94.88it/s]
bootstrap micro f1 95% CI:  78%|██████████▉   | 389/500 [00:04<00:01, 95.18it/s]
bootstrap micro f1 95% CI:  80%|███████████▏  | 399/500 [00:04<00:01, 95.08it/s]
bootstrap micro f1 95% CI:  82%|███████████▍  | 409/500 [00:04<00:00, 95.20it/s]
bootstrap micro f1 95% CI:  84%|███████████▋  | 419/500 [00:04<00:00, 95.25it/s]
bootstrap micro f1 95% CI:  86%|████████████  | 429/500 [00:04<00:00, 95.21it/s]
bootstrap micro f1 95% CI:  88%|████████████▎ | 439/500 [00:04<00:00, 95.23it/s]
bootstrap micro f1 95% CI:  90%|████████████▌ | 449/500 [00:04<00:00, 95.24it/s]
bootstrap micro f1 95% CI:  92%|████████████▊ | 459/500 [00:04<00:00, 94.90it/s]
bootstrap micro f1 95% CI:  94%|█████████████▏| 469/500 [00:04<00:00, 94.66it/s]
bootstrap micro f1 95% CI:  96%|█████████████▍| 479/500 [00:05<00:00, 93.68it/s]
bootstrap micro f1 95% CI:  98%|█████████████▋| 489/500 [00:05<00:00, 93.61it/s]
bootstrap micro f1 95% CI: 100%|█████████████▉| 499/500 [00:05<00:00, 93.62it/s]

bootstrap micro f1 95% CI: 100%|██████████████| 500/500 [00:05<00:00, 93.73it/s]


bootstrap macro f1 95% CI:   2%|▎               | 9/500 [00:00<00:05, 85.59it/s]

bootstrap macro f1 95% CI:   4%|▌              | 19/500 [00:00<00:05, 91.40it/s]

bootstrap macro f1 95% CI:   6%|▊              | 29/500 [00:00<00:05, 93.34it/s]

bootstrap macro f1 95% CI:   8%|█▏             | 39/500 [00:00<00:04, 93.63it/s]

bootstrap macro f1 95% CI:  10%|█▍             | 49/500 [00:00<00:04, 94.31it/s]

bootstrap macro f1 95% CI:  12%|█▊             | 59/500 [00:00<00:04, 94.34it/s]

bootstrap macro f1 95% CI:  14%|██             | 69/500 [00:00<00:04, 94.58it/s]

bootstrap macro f1 95% CI:  16%|██▎            | 79/500 [00:00<00:04, 94.97it/s]

bootstrap macro f1 95% CI:  18%|██▋            | 89/500 [00:00<00:04, 95.11it/s]

bootstrap macro f1 95% CI:  20%|██▉            | 99/500 [00:01<00:04, 94.97it/s]

bootstrap macro f1 95% CI:  22%|███           | 109/500 [00:01<00:04, 95.05it/s]

bootstrap macro f1 95% CI:  24%|███▎          | 119/500 [00:01<00:04, 95.16it/s]

bootstrap macro f1 95% CI:  26%|███▌          | 129/500 [00:01<00:03, 94.88it/s]

bootstrap macro f1 95% CI:  28%|███▉          | 139/500 [00:01<00:03, 94.79it/s]

bootstrap macro f1 95% CI:  30%|████▏         | 149/500 [00:01<00:03, 94.77it/s]

bootstrap macro f1 95% CI:  32%|████▍         | 159/500 [00:01<00:03, 94.90it/s]

bootstrap macro f1 95% CI:  34%|████▋         | 169/500 [00:01<00:03, 94.94it/s]

bootstrap macro f1 95% CI:  36%|█████         | 179/500 [00:01<00:03, 95.12it/s]

bootstrap macro f1 95% CI:  38%|█████▎        | 189/500 [00:01<00:03, 95.23it/s]

bootstrap macro f1 95% CI:  40%|█████▌        | 199/500 [00:02<00:03, 94.45it/s]

bootstrap macro f1 95% CI:  42%|█████▊        | 209/500 [00:02<00:03, 94.49it/s]

bootstrap macro f1 95% CI:  44%|██████▏       | 219/500 [00:02<00:02, 94.82it/s]

bootstrap macro f1 95% CI:  46%|██████▍       | 229/500 [00:02<00:02, 94.84it/s]

bootstrap macro f1 95% CI:  48%|██████▋       | 239/500 [00:02<00:02, 94.76it/s]

bootstrap macro f1 95% CI:  50%|██████▉       | 249/500 [00:02<00:02, 94.74it/s]

bootstrap macro f1 95% CI:  52%|███████▎      | 259/500 [00:02<00:02, 94.94it/s]

bootstrap macro f1 95% CI:  54%|███████▌      | 269/500 [00:02<00:02, 94.67it/s]

bootstrap macro f1 95% CI:  56%|███████▊      | 279/500 [00:02<00:02, 94.71it/s]

bootstrap macro f1 95% CI:  58%|████████      | 289/500 [00:03<00:02, 94.73it/s]

bootstrap macro f1 95% CI:  60%|████████▎     | 299/500 [00:03<00:02, 94.78it/s]

bootstrap macro f1 95% CI:  62%|████████▋     | 309/500 [00:03<00:02, 94.77it/s]

bootstrap macro f1 95% CI:  64%|████████▉     | 319/500 [00:03<00:01, 94.93it/s]

bootstrap macro f1 95% CI:  66%|█████████▏    | 329/500 [00:03<00:01, 94.98it/s]

bootstrap macro f1 95% CI:  68%|█████████▍    | 339/500 [00:03<00:01, 94.83it/s]

bootstrap macro f1 95% CI:  70%|█████████▊    | 349/500 [00:03<00:01, 95.03it/s]

bootstrap macro f1 95% CI:  72%|██████████    | 359/500 [00:03<00:01, 94.79it/s]

bootstrap macro f1 95% CI:  74%|██████████▎   | 369/500 [00:03<00:01, 94.65it/s]

bootstrap macro f1 95% CI:  76%|██████████▌   | 379/500 [00:04<00:01, 94.92it/s]

bootstrap macro f1 95% CI:  78%|██████████▉   | 389/500 [00:04<00:01, 95.26it/s]

bootstrap macro f1 95% CI:  80%|███████████▏  | 399/500 [00:04<00:01, 94.96it/s]

bootstrap macro f1 95% CI:  82%|███████████▍  | 409/500 [00:04<00:00, 95.08it/s]

bootstrap macro f1 95% CI:  84%|███████████▋  | 419/500 [00:04<00:00, 95.01it/s]

bootstrap macro f1 95% CI:  86%|████████████  | 429/500 [00:04<00:00, 95.44it/s]

bootstrap macro f1 95% CI:  88%|████████████▎ | 439/500 [00:04<00:00, 95.36it/s]

bootstrap macro f1 95% CI:  90%|████████████▌ | 449/500 [00:04<00:00, 95.23it/s]

bootstrap macro f1 95% CI:  92%|████████████▊ | 459/500 [00:04<00:00, 95.33it/s]

bootstrap macro f1 95% CI:  94%|█████████████▏| 469/500 [00:04<00:00, 95.43it/s]

bootstrap macro f1 95% CI:  96%|█████████████▍| 479/500 [00:05<00:00, 95.25it/s]

bootstrap macro f1 95% CI:  98%|█████████████▋| 489/500 [00:05<00:00, 95.62it/s]

bootstrap macro f1 95% CI: 100%|█████████████▉| 499/500 [00:05<00:00, 95.47it/s]
bootstrap macro f1 95% CI: 100%|██████████████| 500/500 [00:05<00:00, 94.69it/s]

bootstrap micro f1 95% CI:   3%|▍             | 17/500 [00:00<00:02, 165.33it/s]
bootstrap micro f1 95% CI:   7%|▉             | 35/500 [00:00<00:02, 173.44it/s]
bootstrap micro f1 95% CI:  11%|█▌            | 54/500 [00:00<00:02, 176.79it/s]
bootstrap micro f1 95% CI:  14%|██            | 72/500 [00:00<00:02, 177.71it/s]
bootstrap micro f1 95% CI:  18%|██▌           | 91/500 [00:00<00:02, 178.59it/s]
bootstrap micro f1 95% CI:  22%|██▊          | 110/500 [00:00<00:02, 179.18it/s]
bootstrap micro f1 95% CI:  26%|███▎         | 129/500 [00:00<00:02, 179.48it/s]
bootstrap micro f1 95% CI:  30%|███▊         | 148/500 [00:00<00:01, 180.06it/s]
bootstrap micro f1 95% CI:  33%|████▎        | 167/500 [00:00<00:01, 180.37it/s]
bootstrap micro f1 95% CI:  37%|████▊        | 186/500 [00:01<00:01, 181.15it/s]
bootstrap micro f1 95% CI:  41%|█████▎       | 205/500 [00:01<00:01, 181.42it/s]
bootstrap micro f1 95% CI:  45%|█████▊       | 224/500 [00:01<00:01, 181.00it/s]
bootstrap micro f1 95% CI:  49%|██████▎      | 243/500 [00:01<00:01, 180.45it/s]
bootstrap micro f1 95% CI:  52%|██████▊      | 262/500 [00:01<00:01, 180.56it/s]
bootstrap micro f1 95% CI:  56%|███████▎     | 281/500 [00:01<00:01, 180.12it/s]
bootstrap micro f1 95% CI:  60%|███████▊     | 300/500 [00:01<00:01, 180.39it/s]
bootstrap micro f1 95% CI:  64%|████████▎    | 319/500 [00:01<00:01, 180.06it/s]
bootstrap micro f1 95% CI:  68%|████████▊    | 338/500 [00:01<00:00, 180.17it/s]
bootstrap micro f1 95% CI:  71%|█████████▎   | 357/500 [00:01<00:00, 180.24it/s]
bootstrap micro f1 95% CI:  75%|█████████▊   | 376/500 [00:02<00:00, 179.95it/s]
bootstrap micro f1 95% CI:  79%|██████████▎  | 395/500 [00:02<00:00, 180.17it/s]
bootstrap micro f1 95% CI:  83%|██████████▊  | 414/500 [00:02<00:00, 179.93it/s]
bootstrap micro f1 95% CI:  86%|███████████▏ | 432/500 [00:02<00:00, 179.83it/s]
bootstrap micro f1 95% CI:  90%|███████████▋ | 450/500 [00:02<00:00, 179.84it/s]
bootstrap micro f1 95% CI:  94%|████████████▏| 469/500 [00:02<00:00, 180.13it/s]
bootstrap micro f1 95% CI:  98%|████████████▋| 488/500 [00:02<00:00, 180.14it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:02<00:00, 179.67it/s]


bootstrap macro f1 95% CI:   3%|▍             | 17/500 [00:00<00:02, 167.22it/s]

bootstrap macro f1 95% CI:   7%|█             | 36/500 [00:00<00:02, 175.08it/s]

bootstrap macro f1 95% CI:  11%|█▌            | 55/500 [00:00<00:02, 177.41it/s]

bootstrap macro f1 95% CI:  15%|██            | 74/500 [00:00<00:02, 178.52it/s]

bootstrap macro f1 95% CI:  18%|██▌           | 92/500 [00:00<00:02, 178.06it/s]

bootstrap macro f1 95% CI:  22%|██▊          | 110/500 [00:00<00:02, 178.55it/s]

bootstrap macro f1 95% CI:  26%|███▎         | 129/500 [00:00<00:02, 179.08it/s]

bootstrap macro f1 95% CI:  30%|███▊         | 148/500 [00:00<00:01, 179.46it/s]

bootstrap macro f1 95% CI:  33%|████▎        | 167/500 [00:00<00:01, 179.68it/s]

bootstrap macro f1 95% CI:  37%|████▊        | 185/500 [00:01<00:01, 179.76it/s]

bootstrap macro f1 95% CI:  41%|█████▎       | 204/500 [00:01<00:01, 180.55it/s]

bootstrap macro f1 95% CI:  45%|█████▊       | 223/500 [00:01<00:01, 180.73it/s]

bootstrap macro f1 95% CI:  48%|██████▎      | 242/500 [00:01<00:01, 181.17it/s]

bootstrap macro f1 95% CI:  52%|██████▊      | 261/500 [00:01<00:01, 181.27it/s]

bootstrap macro f1 95% CI:  56%|███████▎     | 280/500 [00:01<00:01, 181.49it/s]

bootstrap macro f1 95% CI:  60%|███████▊     | 299/500 [00:01<00:01, 181.23it/s]

bootstrap macro f1 95% CI:  64%|████████▎    | 318/500 [00:01<00:01, 180.92it/s]

bootstrap macro f1 95% CI:  67%|████████▊    | 337/500 [00:01<00:00, 181.18it/s]

bootstrap macro f1 95% CI:  71%|█████████▎   | 356/500 [00:01<00:00, 181.15it/s]

bootstrap macro f1 95% CI:  75%|█████████▊   | 375/500 [00:02<00:00, 181.30it/s]

bootstrap macro f1 95% CI:  79%|██████████▏  | 394/500 [00:02<00:00, 181.35it/s]

bootstrap macro f1 95% CI:  83%|██████████▋  | 413/500 [00:02<00:00, 181.60it/s]

bootstrap macro f1 95% CI:  86%|███████████▏ | 432/500 [00:02<00:00, 181.98it/s]

bootstrap macro f1 95% CI:  90%|███████████▋ | 451/500 [00:02<00:00, 181.95it/s]

bootstrap macro f1 95% CI:  94%|████████████▏| 470/500 [00:02<00:00, 182.08it/s]

bootstrap macro f1 95% CI:  98%|████████████▋| 489/500 [00:02<00:00, 181.48it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:02<00:00, 179.14it/s]

bootstrap micro f1 95% CI:   2%|▎               | 9/500 [00:00<00:05, 84.80it/s]
bootstrap micro f1 95% CI:   4%|▌              | 19/500 [00:00<00:05, 89.79it/s]
bootstrap micro f1 95% CI:   6%|▊              | 29/500 [00:00<00:05, 90.79it/s]
bootstrap micro f1 95% CI:   8%|█▏             | 39/500 [00:00<00:05, 91.52it/s]
bootstrap micro f1 95% CI:  10%|█▍             | 49/500 [00:00<00:04, 91.77it/s]
bootstrap micro f1 95% CI:  12%|█▊             | 59/500 [00:00<00:04, 92.01it/s]
bootstrap micro f1 95% CI:  14%|██             | 69/500 [00:00<00:04, 92.09it/s]
bootstrap micro f1 95% CI:  16%|██▎            | 79/500 [00:00<00:04, 92.16it/s]
bootstrap micro f1 95% CI:  18%|██▋            | 89/500 [00:00<00:04, 92.29it/s]
bootstrap micro f1 95% CI:  20%|██▉            | 99/500 [00:01<00:04, 92.51it/s]
bootstrap micro f1 95% CI:  22%|███           | 109/500 [00:01<00:04, 92.75it/s]
bootstrap micro f1 95% CI:  24%|███▎          | 119/500 [00:01<00:04, 92.62it/s]
bootstrap micro f1 95% CI:  26%|███▌          | 129/500 [00:01<00:04, 92.68it/s]
bootstrap micro f1 95% CI:  28%|███▉          | 139/500 [00:01<00:03, 92.51it/s]
bootstrap micro f1 95% CI:  30%|████▏         | 149/500 [00:01<00:03, 92.66it/s]
bootstrap micro f1 95% CI:  32%|████▍         | 159/500 [00:01<00:03, 92.61it/s]
bootstrap micro f1 95% CI:  34%|████▋         | 169/500 [00:01<00:03, 92.79it/s]
bootstrap micro f1 95% CI:  36%|█████         | 179/500 [00:01<00:03, 92.55it/s]
bootstrap micro f1 95% CI:  38%|█████▎        | 189/500 [00:02<00:03, 93.06it/s]
bootstrap micro f1 95% CI:  40%|█████▌        | 199/500 [00:02<00:03, 93.09it/s]
bootstrap micro f1 95% CI:  42%|█████▊        | 209/500 [00:02<00:03, 93.22it/s]
bootstrap micro f1 95% CI:  44%|██████▏       | 219/500 [00:02<00:03, 92.65it/s]
bootstrap micro f1 95% CI:  46%|██████▍       | 229/500 [00:02<00:02, 92.82it/s]
bootstrap micro f1 95% CI:  48%|██████▋       | 239/500 [00:02<00:02, 92.80it/s]
bootstrap micro f1 95% CI:  50%|██████▉       | 249/500 [00:02<00:02, 92.69it/s]
bootstrap micro f1 95% CI:  52%|███████▎      | 259/500 [00:02<00:02, 92.75it/s]
bootstrap micro f1 95% CI:  54%|███████▌      | 269/500 [00:02<00:02, 92.73it/s]
bootstrap micro f1 95% CI:  56%|███████▊      | 279/500 [00:03<00:02, 92.60it/s]
bootstrap micro f1 95% CI:  58%|████████      | 289/500 [00:03<00:02, 92.39it/s]
bootstrap micro f1 95% CI:  60%|████████▎     | 299/500 [00:03<00:02, 92.52it/s]
bootstrap micro f1 95% CI:  62%|████████▋     | 309/500 [00:03<00:02, 92.68it/s]
bootstrap micro f1 95% CI:  64%|████████▉     | 319/500 [00:03<00:01, 92.81it/s]
bootstrap micro f1 95% CI:  66%|█████████▏    | 329/500 [00:03<00:01, 92.95it/s]
bootstrap micro f1 95% CI:  68%|█████████▍    | 339/500 [00:03<00:01, 92.94it/s]
bootstrap micro f1 95% CI:  70%|█████████▊    | 349/500 [00:03<00:01, 93.23it/s]
bootstrap micro f1 95% CI:  72%|██████████    | 359/500 [00:03<00:01, 92.98it/s]
bootstrap micro f1 95% CI:  74%|██████████▎   | 369/500 [00:03<00:01, 93.34it/s]
bootstrap micro f1 95% CI:  76%|██████████▌   | 379/500 [00:04<00:01, 93.28it/s]
bootstrap micro f1 95% CI:  78%|██████████▉   | 389/500 [00:04<00:01, 92.90it/s]
bootstrap micro f1 95% CI:  80%|███████████▏  | 399/500 [00:04<00:01, 92.96it/s]
bootstrap micro f1 95% CI:  82%|███████████▍  | 409/500 [00:04<00:00, 92.89it/s]
bootstrap micro f1 95% CI:  84%|███████████▋  | 419/500 [00:04<00:00, 92.86it/s]
bootstrap micro f1 95% CI:  86%|████████████  | 429/500 [00:04<00:00, 92.82it/s]
bootstrap micro f1 95% CI:  88%|████████████▎ | 439/500 [00:04<00:00, 92.71it/s]
bootstrap micro f1 95% CI:  90%|████████████▌ | 449/500 [00:04<00:00, 92.78it/s]
bootstrap micro f1 95% CI:  92%|████████████▊ | 459/500 [00:04<00:00, 92.89it/s]
bootstrap micro f1 95% CI:  94%|█████████████▏| 469/500 [00:05<00:00, 92.94it/s]
bootstrap micro f1 95% CI:  96%|█████████████▍| 479/500 [00:05<00:00, 92.78it/s]
bootstrap micro f1 95% CI:  98%|█████████████▋| 489/500 [00:05<00:00, 92.73it/s]
bootstrap micro f1 95% CI: 100%|█████████████▉| 499/500 [00:05<00:00, 92.73it/s]

bootstrap micro f1 95% CI: 100%|██████████████| 500/500 [00:05<00:00, 92.60it/s]


bootstrap macro f1 95% CI:   2%|▎               | 9/500 [00:00<00:05, 85.25it/s]

bootstrap macro f1 95% CI:   4%|▌              | 19/500 [00:00<00:05, 89.68it/s]

bootstrap macro f1 95% CI:   6%|▊              | 29/500 [00:00<00:05, 90.66it/s]

bootstrap macro f1 95% CI:   8%|█▏             | 39/500 [00:00<00:05, 91.34it/s]

bootstrap macro f1 95% CI:  10%|█▍             | 49/500 [00:00<00:04, 91.79it/s]

bootstrap macro f1 95% CI:  12%|█▊             | 59/500 [00:00<00:04, 91.97it/s]

bootstrap macro f1 95% CI:  14%|██             | 69/500 [00:00<00:04, 92.28it/s]

bootstrap macro f1 95% CI:  16%|██▎            | 79/500 [00:00<00:04, 92.65it/s]

bootstrap macro f1 95% CI:  18%|██▋            | 89/500 [00:00<00:04, 92.68it/s]

bootstrap macro f1 95% CI:  20%|██▉            | 99/500 [00:01<00:04, 92.58it/s]

bootstrap macro f1 95% CI:  22%|███           | 109/500 [00:01<00:04, 92.37it/s]

bootstrap macro f1 95% CI:  24%|███▎          | 119/500 [00:01<00:04, 92.33it/s]

bootstrap macro f1 95% CI:  26%|███▌          | 129/500 [00:01<00:04, 92.60it/s]

bootstrap macro f1 95% CI:  28%|███▉          | 139/500 [00:01<00:03, 92.66it/s]

bootstrap macro f1 95% CI:  30%|████▏         | 149/500 [00:01<00:03, 93.10it/s]

bootstrap macro f1 95% CI:  32%|████▍         | 159/500 [00:01<00:03, 93.12it/s]

bootstrap macro f1 95% CI:  34%|████▋         | 169/500 [00:01<00:03, 93.04it/s]

bootstrap macro f1 95% CI:  36%|█████         | 179/500 [00:01<00:03, 92.96it/s]

bootstrap macro f1 95% CI:  38%|█████▎        | 189/500 [00:02<00:03, 92.94it/s]

bootstrap macro f1 95% CI:  40%|█████▌        | 199/500 [00:02<00:03, 92.72it/s]

bootstrap macro f1 95% CI:  42%|█████▊        | 209/500 [00:02<00:03, 92.91it/s]

bootstrap macro f1 95% CI:  44%|██████▏       | 219/500 [00:02<00:03, 93.02it/s]

bootstrap macro f1 95% CI:  46%|██████▍       | 229/500 [00:02<00:02, 92.88it/s]

bootstrap macro f1 95% CI:  48%|██████▋       | 239/500 [00:02<00:02, 92.71it/s]

bootstrap macro f1 95% CI:  50%|██████▉       | 249/500 [00:02<00:02, 93.12it/s]

bootstrap macro f1 95% CI:  52%|███████▎      | 259/500 [00:02<00:02, 93.22it/s]

bootstrap macro f1 95% CI:  54%|███████▌      | 269/500 [00:02<00:02, 92.29it/s]

bootstrap macro f1 95% CI:  56%|███████▊      | 279/500 [00:03<00:02, 92.33it/s]

bootstrap macro f1 95% CI:  58%|████████      | 289/500 [00:03<00:02, 92.26it/s]

bootstrap macro f1 95% CI:  60%|████████▎     | 299/500 [00:03<00:02, 92.30it/s]

bootstrap macro f1 95% CI:  62%|████████▋     | 309/500 [00:03<00:02, 92.43it/s]


In [48]:
!python ../llava/eval/rrg_eval/run.py ../results/llavarad/race_black.jsonl --run_name race_black

[2025-07-04 18:26:37,112] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CheXbert:   0%|                                           | 0/5 [00:00<?, ?it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

bootstrap micro f1 95% CI:   0%|                        | 0/500 [00:00<?, ?it/s]
bootstrap micro f1 95% CI:   5%|▋             | 26/500 [00:00<00:01, 252.52it/s]
bootstrap micro f1 95% CI:  11%|█▍            | 53/500 [00:00<00:01, 258.56it/s]
bootstrap micro f1 95% CI:  16%|██▏           | 80/500 [00:00<00:01, 260.93it/s]
bootstrap micro f1 95% CI:  21%|██▊          | 107/500 [00:00<00:01, 261.77it/s]
bootstrap micro f1 95% CI:  27%|███▍         | 134/500 [00:00<00:01, 262.43it/s]
bootstrap micro f1 95% CI:  32%|████▏        | 161/500 [00:00<00:01, 262.75it/s]
bootstrap micro f1 95% CI:  38%|████▉        | 188/500 [00:00<00:01, 263.31it/s]
bootstrap micro f1 95% CI:  43%|█████▌       | 215/500 [00:00<00:01, 263.33it/s]
bootstrap micro f1 95% CI:  48%|██████▎      | 242/500 [00:00<00:00, 260.30it/s]
bootstrap micro f1 95% CI:  54%|██████▉      | 269/500 [00:01<00:00, 261.42it/s]
bootstrap micro f1 95% CI:  59%|███████▋     | 296/500 [00:01<00:00, 262.21it/s]
bootstrap micro f1 95% CI:  65%|████████▍    | 323/500 [00:01<00:00, 262.88it/s]
bootstrap micro f1 95% CI:  70%|█████████    | 350/500 [00:01<00:00, 263.10it/s]
bootstrap micro f1 95% CI:  75%|█████████▊   | 377/500 [00:01<00:00, 263.56it/s]
bootstrap micro f1 95% CI:  81%|██████████▌  | 404/500 [00:01<00:00, 263.88it/s]
bootstrap micro f1 95% CI:  86%|███████████▏ | 431/500 [00:01<00:00, 263.95it/s]
bootstrap micro f1 95% CI:  92%|███████████▉ | 458/500 [00:01<00:00, 261.82it/s]
bootstrap micro f1 95% CI:  97%|████████████▌| 485/500 [00:01<00:00, 262.68it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 262.23it/s]


bootstrap macro f1 95% CI:   5%|▊             | 27/500 [00:00<00:01, 261.78it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


bootstrap macro f1 95% CI:  11%|█▌            | 54/500 [00:00<00:01, 262.78it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


bootstrap macro f1 95% CI:  16%|██▎           | 81/500 [00:00<00:01, 265.17it/s]

bootstrap macro f1 95% CI:  22%|██▊          | 108/500 [00:00<00:01, 266.90it/s]

bootstrap macro f1 95% CI:  27%|███▌         | 135/500 [00:00<00:01, 267.44it/s]

bootstrap macro f1 95% CI:  32%|████▏        | 162/500 [00:00<00:01, 267.40it/s]

bootstrap macro f1 95% CI:  38%|████▉        | 189/500 [00:00<00:01, 265.72it/s]

bootstrap macro f1 95% CI:  43%|█████▌       | 216/500 [00:00<00:01, 265.97it/s]

bootstrap macro f1 95% CI:  49%|██████▎      | 243/500 [00:00<00:00, 266.51it/s]

bootstrap macro f1 95% CI:  54%|███████      | 270/500 [00:01<00:00, 266.75it/s]

bootstrap macro f1 95% CI:  59%|███████▋     | 297/500 [00:01<00:00, 266.88it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


bootstrap macro f1 95% CI:  65%|████████▍    | 324/500 [00:01<00:00, 266.91it/s]

bootstrap macro f1 95% CI:  70%|█████████▏   | 351/500 [00:01<00:00, 267.04it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


bootstrap macro f1 95% CI:  76%|█████████▊   | 378/500 [00:01<00:00, 267.20it/s]

bootstrap macro f1 95% CI:  81%|██████████▌  | 405/500 [00:01<00:00, 267.22it/s]

bootstrap macro f1 95% CI:  86%|███████████▏ | 432/500 [00:01<00:00, 265.86it/s]

bootstrap macro f1 95% CI:  92%|███████████▉ | 459/500 [00:01<00:00, 266.39it/s]

bootstrap macro f1 95% CI:  97%|████████████▋| 486/500 [00:01<00:00, 267.05it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 265.74it/s]

bootstrap micro f1 95% CI:   9%|█▏            | 44/500 [00:00<00:01, 431.73it/s]
bootstrap micro f1 95% CI:  18%|██▍           | 89/500 [00:00<00:00, 437.13it/s]
bootstrap micro f1 95% CI:  27%|███▍         | 134/500 [00:00<00:00, 439.14it/s]
bootstrap micro f1 95% CI:  36%|████▋        | 179/500 [00:00<00:00, 440.48it/s]
bootstrap micro f1 95% CI:  45%|█████▊       | 224/500 [00:00<00:00, 438.56it/s]
bootstrap micro f1 95% CI:  54%|██████▉      | 269/500 [00:00<00:00, 440.76it/s]
bootstrap micro f1 95% CI:  63%|████████▏    | 314/500 [00:00<00:00, 442.05it/s]
bootstrap micro f1 95% CI:  72%|█████████▎   | 359/500 [00:00<00:00, 443.16it/s]
bootstrap micro f1 95% CI:  81%|██████████▌  | 404/500 [00:00<00:00, 443.54it/s]
bootstrap micro f1 95% CI:  90%|███████████▋ | 449/500 [00:01<00:00, 443.72it/s]
bootstrap micro f1 95% CI:  99%|████████████▊| 494/500 [00:01<00:00, 443.76it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 441.52it/s]


bootstrap macro f1 95% CI:   9%|█▏            | 44/500 [00:00<00:01, 438.07it/s]

bootstrap macro f1 95% CI:  18%|██▍           | 89/500 [00:00<00:00, 443.62it/s]

bootstrap macro f1 95% CI:  27%|███▍         | 134/500 [00:00<00:00, 440.50it/s]

bootstrap macro f1 95% CI:  36%|████▋        | 179/500 [00:00<00:00, 442.61it/s]

bootstrap macro f1 95% CI:  45%|█████▊       | 224/500 [00:00<00:00, 444.35it/s]

bootstrap macro f1 95% CI:  54%|██████▉      | 269/500 [00:00<00:00, 445.33it/s]

bootstrap macro f1 95% CI:  63%|████████▏    | 314/500 [00:00<00:00, 445.57it/s]

bootstrap macro f1 95% CI:  72%|█████████▎   | 359/500 [00:00<00:00, 446.08it/s]

bootstrap macro f1 95% CI:  81%|██████████▌  | 404/500 [00:00<00:00, 445.95it/s]

bootstrap macro f1 95% CI:  90%|███████████▋ | 449/500 [00:01<00:00, 446.16it/s]

bootstrap macro f1 95% CI:  99%|████████████▊| 494/500 [00:01<00:00, 442.92it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 440.51it/s]

bootstrap micro f1 95% CI:   5%|▋             | 26/500 [00:00<00:01, 255.58it/s]
bootstrap micro f1 95% CI:  11%|█▍            | 53/500 [00:00<00:01, 258.98it/s]
bootstrap micro f1 95% CI:  16%|██▏           | 80/500 [00:00<00:01, 259.52it/s]
bootstrap micro f1 95% CI:  21%|██▊          | 107/500 [00:00<00:01, 259.90it/s]
bootstrap micro f1 95% CI:  27%|███▍         | 133/500 [00:00<00:01, 259.70it/s]
bootstrap micro f1 95% CI:  32%|████▏        | 159/500 [00:00<00:01, 259.65it/s]
bootstrap micro f1 95% CI:  37%|████▊        | 185/500 [00:00<00:01, 259.64it/s]
bootstrap micro f1 95% CI:  42%|█████▍       | 211/500 [00:00<00:01, 258.47it/s]
bootstrap micro f1 95% CI:  47%|██████▏      | 237/500 [00:00<00:01, 258.90it/s]
bootstrap micro f1 95% CI:  53%|██████▊      | 263/500 [00:01<00:00, 258.99it/s]
bootstrap micro f1 95% CI:  58%|███████▌     | 289/500 [00:01<00:00, 259.05it/s]
bootstrap micro f1 95% CI:  63%|████████▏    | 315/500 [00:01<00:00, 259.30it/s]
bootstrap micro f1 95% CI:  68%|████████▉    | 342/500 [00:01<00:00, 259.52it/s]
bootstrap micro f1 95% CI:  74%|█████████▌   | 369/500 [00:01<00:00, 259.74it/s]
bootstrap micro f1 95% CI:  79%|██████████▎  | 395/500 [00:01<00:00, 259.78it/s]
bootstrap micro f1 95% CI:  84%|██████████▉  | 421/500 [00:01<00:00, 259.83it/s]
bootstrap micro f1 95% CI:  89%|███████████▌ | 447/500 [00:01<00:00, 259.73it/s]
bootstrap micro f1 95% CI:  95%|████████████▎| 473/500 [00:01<00:00, 259.78it/s]
bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 259.90it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 259.38it/s]


bootstrap macro f1 95% CI:   5%|▋             | 26/500 [00:00<00:01, 255.19it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


bootstrap macro f1 95% CI:  11%|█▍            | 53/500 [00:00<00:01, 258.53it/s]

bootstrap macro f1 95% CI:  16%|██▏           | 80/500 [00:00<00:01, 259.28it/s]

bootstrap macro f1 95% CI:  21%|██▊          | 107/500 [00:00<00:01, 260.02it/s]

bootstrap macro f1 95% CI:  27%|███▍         | 134/500 [00:00<00:01, 259.86it/s]

bootstrap macro f1 95% CI:  32%|████▏        | 160/500 [00:00<00:01, 257.00it/s]

bootstrap macro f1 95% CI:  37%|████▊        | 187/500 [00:00<00:01, 258.18it/s]

bootstrap macro f1 95% CI:  43%|█████▌       | 214/500 [00:00<00:01, 259.29it/s]

bootstrap macro f1 95% CI:  48%|██████▎      | 241/500 [00:00<00:00, 260.22it/s]

bootstrap macro f1 95% CI:  54%|██████▉      | 268/500 [00:01<00:00, 260.24it/s]

bootstrap macro f1 95% CI:  59%|███████▋     | 295/500 [00:01<00:00, 260.20it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


bootstrap macro f1 95% CI:  64%|████████▎    | 322/500 [00:01<00:00, 260.53it/s]

bootstrap macro f1 95% CI:  70%|█████████    | 349/500 [00:01<00:00, 260.49it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


bootstrap macro f1 95% CI:  75%|█████████▊   | 376/500 [00:01<00:00, 260.17it/s]

bootstrap macro f1 95% CI:  81%|██████████▍  | 403/500 [00:01<00:00, 260.28it/s]

bootstrap macro f1 95% CI:  86%|███████████▏ | 430/500 [00:01<00:00, 260.44it/s]

bootstrap macro f1 95% CI:  91%|███████████▉ | 457/500 [00:01<00:00, 260.45it/s]

bootstrap macro f1 95% CI:  97%|████████████▌| 484/500 [00:01<00:00, 260.52it/s]
bootstrap macro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 259.10it/s]

bootstrap micro f1 95% CI:   9%|█▏            | 43/500 [00:00<00:01, 428.13it/s]
bootstrap micro f1 95% CI:  17%|██▍           | 87/500 [00:00<00:00, 433.19it/s]
bootstrap micro f1 95% CI:  26%|███▍         | 131/500 [00:00<00:00, 434.84it/s]
bootstrap micro f1 95% CI:  35%|████▌        | 176/500 [00:00<00:00, 437.09it/s]
bootstrap micro f1 95% CI:  44%|█████▋       | 221/500 [00:00<00:00, 438.17it/s]
bootstrap micro f1 95% CI:  53%|██████▉      | 265/500 [00:00<00:00, 436.94it/s]
bootstrap micro f1 95% CI:  62%|████████     | 310/500 [00:00<00:00, 438.18it/s]
bootstrap micro f1 95% CI:  71%|█████████▏   | 355/500 [00:00<00:00, 439.18it/s]
bootstrap micro f1 95% CI:  80%|██████████▍  | 400/500 [00:00<00:00, 439.77it/s]
bootstrap micro f1 95% CI:  89%|███████████▌ | 445/500 [00:01<00:00, 440.36it/s]
bootstrap micro f1 95% CI:  98%|████████████▋| 490/500 [00:01<00:00, 440.74it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:01<00:00, 438.24it/s]


bootstrap macro f1 95% CI:   9%|█▏            | 44/500 [00:00<00:01, 432.35it/s]

bootstrap macro f1 95% CI:  18%|██▍           | 88/500 [00:00<00:00, 436.76it/s]

bootstrap macro f1 95% CI:  26%|███▍         | 132/500 [00:00<00:00, 437.97it/s]

bootstrap macro f1 95% CI:  35%|████▌        | 176/500 [00:00<00:00, 438.52it/s]

bootstrap macro f1 95% CI:  44%|█████▋       | 220/500 [00:00<00:00, 438.78it/s]

bootstrap macro f1 95% CI:  53%|██████▊      | 264/500 [00:00<00:00, 438.88it/s]

bootstrap macro f1 95% CI:  62%|████████     | 308/500 [00:00<00:00, 438.90it/s]

bootstrap macro f1 95% CI:  71%|█████████▏   | 353/500 [00:00<00:00, 439.45it/s]

bootstrap macro f1 95% CI:  79%|██████████▎  | 397/500 [00:00<00:00, 439.44it/s]

bootstrap macro f1 95% CI:  88%|███████████▍ | 441/500 [00:01<00:00, 438.99it/s]

F1-RadGraph:  20%|██████▍                         | 1/5 [00:18<01:14, 18.64s/it]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
ROUGE-L: 100%|████████████████████████████████████| 5/5 [00:41<00:00,  8.37s/it]


Total reports: 489

========== Main Results ==========
        Micro-F1-14  Micro-F1-5  Macro-F1-14  ...     BLEU-1     BLEU-4   ROUGE-L
median     0.572499    0.592562     0.390428  ...  38.969791  15.771871  0.313976
ci_l       0.545404    0.562722     0.343372  ...  37.358967  14.554789  0.302536
ci_h       0.600104    0.626955     0.438608  ...  40.427350  16.897531  0.325927

[3 rows x 12 columns]

wandb: Currently logged in as: mbhosale (bhosalems_) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.20.1
wandb: Run data is saved locally in /home/csgrad/mbhosale/phd/MrFair/LLaVA-Rad/scripts/wandb/run-20250704_182722-race_black
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run race_black
wandb: ⭐️ View project at https://wandb.ai/bhosalems_/LLaVA-Rad-llava_eval_rrg_eval
wandb: 🚀 View run at https://wandb.ai/bhosalems_/LLaVA-Rad-llava_eval_rrg_eval/runs/race_black
========== CheXbert F1 (uncertain as positive) ==========
                            f1-score  precision    recall  support
Atelectasis                 0.487455   0.515152  0.462585    147.0
Cardiomegaly                0.713427   0.698039  0.729508    244.0
Consolidation               0.285714   0.333333  0.250000     40.0
Edema                       0.576779   0.606299  0.550000    140.0
Enlarged Cardiomediastinum  0.434483   0.463235  0.409091    154.0
Fracture                    0.300000   0.375000  0.250000     12.0
Lung Lesion                 0.137931   0.400000  0.083333     24.0
Lung Opacity                0.473333   0.529851  0.427711    166.0
No Finding                  0.390244   0.326531  0.484848     33.0
Pleural Effusion            0.655172   0.712500  0.606383    188.0
Pleural Other               0.206897   0.300000  0.157895     19.0
Pneumonia                   0.298246   0.340000  0.265625     64.0
Pneumothorax                0.200000   0.250000  0.166667     12.0
Support Devices             0.846797   0.853933  0.839779    181.0
micro avg                   0.573540   0.605304  0.544944   1424.0
macro avg                   0.429034   0.478848  0.405959   1424.0

========== CheXbert F1 (uncertain as negative) ==========
                            f1-score  precision    recall  support
Atelectasis                 0.378378   0.392523  0.365217    115.0
Cardiomegaly                0.720524   0.708155  0.733333    225.0
Consolidation               0.228571   0.266667  0.200000     20.0
Edema                       0.506024   0.531646  0.482759     87.0
Enlarged Cardiomediastinum  0.187500   0.195652  0.180000     50.0
Fracture                    0.333333   0.375000  0.300000     10.0
Lung Lesion                 0.142857   0.400000  0.086957     23.0
Lung Opacity                0.474916   0.529851  0.430303    165.0
No Finding                  0.390244   0.326531  0.484848     33.0
Pleural Effusion            0.650847   0.700730  0.607595    158.0
Pleural Other               0.173913   0.222222  0.142857     14.0
Pneumonia                   0.228571   0.285714  0.190476     21.0
Pneumothorax                0.307692   0.333333  0.285714      7.0
Support Devices             0.846797   0.853933  0.839779    181.0
micro avg                   0.573039   0.598039  0.550045   1109.0
macro avg                   0.397869   0.437283  0.380703   1109.0

wandb:
wandb: 🚀 View run race_black at: https://wandb.ai/bhosalems_/LLaVA-Rad-llava_eval_rrg_eval/runs/race_black
wandb: Find logs at: wandb/run-20250704_182722-race_black/logs
bootstrap macro f1 95% CI: 100%|██████████████| 500/500 [00:26<00:00, 18.55it/s]

In [49]:
!python ../llava/eval/rrg_eval/run.py ../results/llavarad/race_asian.jsonl --run_name race_asian

[2025-07-04 18:27:30,032] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CheXbert:   0%|                                           | 0/5 [00:00<?, ?it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

bootstrap micro f1 95% CI:   0%|                        | 0/500 [00:00<?, ?it/s]
bootstrap micro f1 95% CI:  15%|██▏           | 76/500 [00:00<00:00, 754.19it/s]
bootstrap micro f1 95% CI:  31%|███▉         | 153/500 [00:00<00:00, 760.02it/s]
bootstrap micro f1 95% CI:  46%|██████       | 231/500 [00:00<00:00, 765.15it/s]
bootstrap micro f1 95% CI:  62%|████████     | 309/500 [00:00<00:00, 767.61it/s]
bootstrap micro f1 95% CI:  77%|██████████   | 387/500 [00:00<00:00, 769.84it/s]
bootstrap micro f1 95% CI:  93%|████████████ | 465/500 [00:00<00:00, 770.90it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:00<00:00, 767.48it/s]
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [50]:
!python ../llava/eval/rrg_eval/run.py ../results/llavarad/race_hispanic.jsonl --run_name race_hispanic

[2025-07-04 18:27:55,769] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CheXbert:   0%|                                           | 0/5 [00:00<?, ?it/s]/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

bootstrap micro f1 95% CI:   0%|                        | 0/500 [00:00<?, ?it/s]
bootstrap micro f1 95% CI:  17%|██▎           | 83/500 [00:00<00:00, 829.02it/s]
bootstrap micro f1 95% CI:  34%|████▍        | 170/500 [00:00<00:00, 847.63it/s]
bootstrap micro f1 95% CI:  52%|██████▋      | 258/500 [00:00<00:00, 858.38it/s]
bootstrap micro f1 95% CI:  69%|████████▉    | 346/500 [00:00<00:00, 865.79it/s]
bootstrap micro f1 95% CI:  87%|███████████▎ | 435/500 [00:00<00:00, 871.06it/s]

bootstrap micro f1 95% CI: 100%|█████████████| 500/500 [00:00<00:00, 863.75it/s]
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/csgrad/mbhosale/anaconda3/envs/llavarad/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
# Lets check the